// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Direction, State } from '../../types';
import { GlowstonePacket } from '../../packet';
import { PacketReader, PacketWriter } from '../../buffer';

class ClientboundPongResponsePacket extends GlowstonePacket {
	override id = 0x01;
	override state = State.Status;
	override direction = Direction.Clientbound;

	constructor(
		public timestamp: bigint,
	) {
		super();
	}

	serialize() {
		const writer = new PacketWriter();
		writer.writeLong(this.timestamp);
		return writer.finish();
	}

	static override deserialize(bytes: Uint8Array): ClientboundPongResponsePacket {
		const reader = new PacketReader(bytes);
		const timestamp = reader.readLong();
		return new ClientboundPongResponsePacket(timestamp);
	}
}

export { ClientboundPongResponsePacket };