// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Direction, State } from '../../types';
import { GlowstonePacket } from '../../packet';
import { PacketReader, PacketWriter } from '../../buffer';

type Version = {
	name: string;
	protocol: number;
}

type PlayerEntry = {
	id: string;
	name: string;
}

type Players = {
	max: number;
	online: number;
	sample: PlayerEntry[];
}

class ClientboundStatusResponsePacket extends GlowstonePacket {
	override id = 0x00;
	override state = State.Status;
	override direction = Direction.Clientbound;

	constructor(
		public version: Version,
		public enforcesSecureChat: boolean,
		public players?: Players,
		public description?: string,
		public favicon?: string,
	) {
		super();
	}

	serialize() {
		const writer = new PacketWriter();
		writer.writeString(JSON.stringify({
			version: this.version,
			players: this.players,
			description: this.description,
			favicon: this.favicon,
			enforcesSecureChat: this.enforcesSecureChat,
		}));
		return writer.finish();
	}

	static override deserialize(bytes: Uint8Array): ClientboundStatusResponsePacket {
		const reader = new PacketReader(bytes);
		const jsonString = reader.readString();
		const data = JSON.parse(jsonString);
		return new ClientboundStatusResponsePacket(
			data.version,
			data.enforcesSecureChat,
			data.players,
			data.description,
			data.favicon,
		);
	}
}

export { ClientboundStatusResponsePacket };