// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State } from '../../types';

type Version = {
	name: string;
	protocol: number;
}

type PlayerEntry = {
	id: string;
	name: string;
}

type Players = {
	max: number;
	online: number;
	sample: PlayerEntry[];
}

export class ClientboundStatusResponsePacket extends DripleafPacket {
	static readonly id = 0x00;
	static readonly state = State.Status;
	static readonly direction = Direction.Clientbound;

	override readonly id = ClientboundStatusResponsePacket.id;
	override readonly state = ClientboundStatusResponsePacket.state;
	override readonly direction = ClientboundStatusResponsePacket.direction;

	constructor(
		public version: Version,
		public enforcesSecureChat: boolean,
		public players?: Players,
		public description?: string,
		public favicon?: string,
	) {
		super();
	}

	write(writer: PacketWriter) {
		writer.writeString(JSON.stringify({
			version: this.version,
			players: this.players,
			description: this.description,
			favicon: this.favicon,
			enforcesSecureChat: this.enforcesSecureChat,
		}));
	}

	static read(reader: PacketReader): ClientboundStatusResponsePacket {
		const jsonString = reader.readString();
		const data = JSON.parse(jsonString);
		return new ClientboundStatusResponsePacket(
			data.version,
			data.enforcesSecureChat,
			data.players,
			data.description,
			data.favicon,
		);
	}
}