// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State } from '../../types';

export class ServerboundStatusRequestPacket extends DripleafPacket {
	static readonly id = 0x00;
	static readonly state = State.Status;
	static readonly direction = Direction.Serverbound;

	override readonly id = ServerboundStatusRequestPacket.id;
	override readonly state = ServerboundStatusRequestPacket.state;
	override readonly direction = ServerboundStatusRequestPacket.direction;

	constructor() {
		super();
	}

	write(writer: PacketWriter) {
		return new Uint8Array();
	}

	static read(reader: PacketReader): ServerboundStatusRequestPacket {
		return new ServerboundStatusRequestPacket();
	}
}