// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Direction, State } from '../../types';
import { GlowstonePacket } from '../../packet';
import { PacketReader, PacketWriter } from '../../buffer';

class ServerboundStatusRequestPacket extends GlowstonePacket {
	override id = 0x00;
	override state = State.Status;
	override direction = Direction.Serverbound;

	constructor() {
		super();
	}

	serialize() {
		return new Uint8Array();
	}

	static override deserialize(bytes: Uint8Array): ServerboundStatusRequestPacket {
		return new ServerboundStatusRequestPacket();
	}
}

export { ServerboundStatusRequestPacket };