// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import type { Vec3 } from 'vec3';
import type { UUID } from 'node:crypto';

export class ClientboundAddEntityPacket extends DripleafPacket {
	static readonly codec = packetCodec<ClientboundAddEntityPacket>({
		encode(writer: PacketWriter, value: ClientboundAddEntityPacket) {
		writer.writeVarInt(value.entityId);
		writer.writeUUID(value.entityUuid);
		writer.writeVarInt(value.type);
		writer.writeDouble(value.x);
		writer.writeDouble(value.y);
		writer.writeDouble(value.z);
		writer.writeLpVec3(value.movement);
		writer.writeByte(value.pitch);
		writer.writeByte(value.yaw);
		writer.writeByte(value.headYaw);
		writer.writeVarInt(value.data);
		},
		decode(reader: PacketReader): ClientboundAddEntityPacket {
		const entityId = reader.readVarInt();
		const entityUuid = reader.readUUID();
		const type = reader.readVarInt();
		const x = reader.readDouble();
		const y = reader.readDouble();
		const z = reader.readDouble();
		const movement = reader.readLpVec3();
		const pitch = reader.readByte();
		const yaw = reader.readByte();
		const headYaw = reader.readByte();
		const data = reader.readVarInt();
		return new ClientboundAddEntityPacket(entityId, entityUuid, type, x, y, z, movement, pitch, yaw, headYaw, data);
		},
	});

	constructor(
		public entityId: number,
		public entityUuid: UUID,
		public type: number, // todo: Registries.ENTITY_TYPE
		public x: number,
		public y: number,
		public z: number,
		public movement: Vec3,
		public pitch: number,
		public yaw: number,
		public headYaw: number,
		public data: number,
	) {
		super();
	}

}
