// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundAnimatePacket extends DripleafPacket {
	static readonly codec = packetCodec<ClientboundAnimatePacket>({
		encode(writer: PacketWriter, value: ClientboundAnimatePacket) {
		writer.writeVarInt(value.entityId);
		writer.writeUnsignedByte(value.animation);
		},
		decode(reader: PacketReader): ClientboundAnimatePacket {
		const entityId = reader.readVarInt();
		const animation = reader.readUnsignedByte();
		return new ClientboundAnimatePacket(entityId, animation);
		},
	});

	constructor(
		public entityId: number,
		public animation: number
	) {
		super();
	}

}
