// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State } from '../../types';

export class ClientboundAnimatePacket extends DripleafPacket {
	static readonly id = 0x02;
	static readonly state = State.Play;
	static readonly direction = Direction.Clientbound;

	override readonly id = ClientboundAnimatePacket.id;
	override readonly state = ClientboundAnimatePacket.state;
	override readonly direction = ClientboundAnimatePacket.direction;

	constructor(
		public entityId: number,
		public animation: number
	) {
		super();
	}

	write(writer: PacketWriter) {
		writer.writeVarInt(this.entityId);
		writer.writeUnsignedByte(this.animation);
	}

	static read(reader: PacketReader): ClientboundAnimatePacket {
		const entityId = reader.readVarInt();
		const animation = reader.readUnsignedByte();
		return new ClientboundAnimatePacket(entityId, animation);
	}
}