// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundAnimatePacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundAnimatePacket, {
		entityId: Codecs.varInt,
		animation: Codecs.unsignedByte,
	});

	constructor(
		public entityId: number,
		public animation: number
	) {
		super();
	}
}