// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State } from '../../types';

type StatisticEntry = {
	category: number;
	id: number;
	value: number;
};

export class ClientboundAwardStatsPacket extends DripleafPacket {
	static readonly id = 0x03;
	static readonly state = State.Play;
	static readonly direction = Direction.Clientbound;

	override readonly id = ClientboundAwardStatsPacket.id;
	override readonly state = ClientboundAwardStatsPacket.state;
	override readonly direction = ClientboundAwardStatsPacket.direction;

	constructor(
		public statistics: StatisticEntry[]
	) {
		super();
	}

	write(writer: PacketWriter) {
		writer.writeArray(this.statistics, (stat) => {
			writer.writeVarInt(stat.category);
			writer.writeVarInt(stat.id);
			writer.writeVarInt(stat.value);
		});
	}

	static read(reader: PacketReader): ClientboundAwardStatsPacket {
		const statistics = reader.readArray(() => {
			const category = reader.readVarInt();
			const id = reader.readVarInt();
			const value = reader.readVarInt();
			return { category, id, value };
		});
		return new ClientboundAwardStatsPacket(statistics);
	}
}