// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

type StatisticEntry = {
	category: number;
	id: number;
	value: number;
};

export class ClientboundAwardStatsPacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundAwardStatsPacket, {
		statistics: Codecs.array({
			encode(writer, value) {
				writer.writeVarInt(value.category);
				writer.writeVarInt(value.id);
				writer.writeVarInt(value.value);
			},
			decode(reader) {
				const category = reader.readVarInt();
				const id = reader.readVarInt();
				const value = reader.readVarInt();
				return { category, id, value };
			},
		})
	});

	constructor(
		public statistics: StatisticEntry[]
	) {
		super();
	}
}