// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import type { Vec3 } from 'vec3';

export class ClientboundBlockUpdatePacket extends DripleafPacket {
	static readonly codec = packetCodec<ClientboundBlockUpdatePacket>({
		encode(writer: PacketWriter, value: ClientboundBlockUpdatePacket) {
		writer.writeBlockPos(value.position);
		writer.writeVarInt(value.blockState);
		},
		decode(reader: PacketReader): ClientboundBlockUpdatePacket {
		const position = reader.readBlockPos();
		const blockState = reader.readVarInt();
		return new ClientboundBlockUpdatePacket(position, blockState);
		},
	});

	constructor(
		public position: Vec3,
		public blockState: number // todo: registry
	) {
		super();
	}

}
