// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State } from '../../types';
import type { Vec3 } from 'vec3';

export class ClientboundBlockUpdatePacket extends DripleafPacket {
	static readonly id = 0x08;
	static readonly state = State.Play;
	static readonly direction = Direction.Clientbound;

	override readonly id = ClientboundBlockUpdatePacket.id;
	override readonly state = ClientboundBlockUpdatePacket.state;
	override readonly direction = ClientboundBlockUpdatePacket.direction;

	constructor(
		public position: Vec3,
		public blockState: number // todo: registry
	) {
		super();
	}

	write(writer: PacketWriter) {
		writer.writeBlockPos(this.position);
		writer.writeVarInt(this.blockState);
	}

	static read(reader: PacketReader): ClientboundBlockUpdatePacket {
		const position = reader.readBlockPos();
		const blockState = reader.readVarInt();
		return new ClientboundBlockUpdatePacket(position, blockState);
	}
}