// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State } from '../../types';
import type { UnnamedNbtTag } from '@dripleaf/nbt';
import type { Vec3 } from 'vec3';

export class ClientboundBlockEntityDataPacket extends DripleafPacket {
	static readonly id = 0x06;
	static readonly state = State.Play;
	static readonly direction = Direction.Clientbound;

	override readonly id = ClientboundBlockEntityDataPacket.id;
	override readonly state = ClientboundBlockEntityDataPacket.state;
	override readonly direction = ClientboundBlockEntityDataPacket.direction;

	constructor(
		public position: Vec3,
		public type: number, // todo: registry
		public data: UnnamedNbtTag
	) {
		super();
	}

	write(writer: PacketWriter) {
		writer.writeBlockPos(this.position);
		writer.writeUnsignedByte(this.type);
		writer.writeNbt(this.data);
	}

	static read(reader: PacketReader): ClientboundBlockEntityDataPacket {
		const position = reader.readBlockPos();
		const type = reader.readUnsignedByte();
		const data = reader.readNbt();
		return new ClientboundBlockEntityDataPacket(position, type, data);
	}
}