// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { BlockEntityType } from '@dripleaf/registry';
import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import type { UnnamedNbtTag } from '@dripleaf/nbt';
import type { Vec3 } from 'vec3';

export class ClientboundBlockEntityDataPacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundBlockEntityDataPacket, {
		position: Codecs.blockPos,
		type: Codecs.varIntEnum(BlockEntityType),
		data: Codecs.nbt,
	});

	constructor(
		public position: Vec3,
		public type: BlockEntityType,
		public data: UnnamedNbtTag
	) {
		super();
	}
}