// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State } from '../../types';
import type { Vec3 } from 'vec3';

export class ClientboundBlockDestructionPacket extends DripleafPacket {
	static readonly id = 0x05;
	static readonly state = State.Play;
	static readonly direction = Direction.Clientbound;

	override readonly id = ClientboundBlockDestructionPacket.id;
	override readonly state = ClientboundBlockDestructionPacket.state;
	override readonly direction = ClientboundBlockDestructionPacket.direction;

	constructor(
		public entityId: number,
		public position: Vec3,
		public progress: number
	) {
		super();
	}

	write(writer: PacketWriter) {
		writer.writeVarInt(this.entityId);
		writer.writeBlockPos(this.position);
		writer.writeUnsignedByte(this.progress);
	}

	static read(reader: PacketReader): ClientboundBlockDestructionPacket {
		const entityId = reader.readVarInt();
		const position = reader.readBlockPos();
		const progress = reader.readUnsignedByte();
		return new ClientboundBlockDestructionPacket(entityId, position, progress);
	}
}