// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { BlockType } from '@dripleaf/registry';
import { BlockPos } from '@dripleaf/core';
import { BlockPosCodec } from '../../datatypes/BlockPos';
import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundBlockEventPacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundBlockEventPacket, {
		position: BlockPosCodec,
		actionId: Codecs.unsignedByte,
		actionParameter: Codecs.unsignedByte,
		blockType: Codecs.varIntEnum(BlockType),
	});

	constructor(
		public position: BlockPos,
		public actionId: number,
		public actionParameter: number,
		public blockType: BlockType
	) {
		super();
	}
}