// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import type { Vec3 } from 'vec3';

export class ClientboundBlockDestructionPacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundBlockDestructionPacket, {
		entityId: Codecs.varInt,
		position: Codecs.blockPos,
		progress: Codecs.unsignedByte,
	});

	constructor(
		public entityId: number,
		public position: Vec3,
		public progress: number
	) {
		super();
	}
}