// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundBlockChangedAckPacket extends DripleafPacket {
	static readonly codec = packetCodec<ClientboundBlockChangedAckPacket>({
		encode(writer: PacketWriter, value: ClientboundBlockChangedAckPacket) {
		writer.writeVarInt(value.sequenceId);
		},
		decode(reader: PacketReader): ClientboundBlockChangedAckPacket {
		const sequenceId = reader.readVarInt();
		return new ClientboundBlockChangedAckPacket(sequenceId);
		},
	});

	constructor(
		public sequenceId: number,
	) {
		super();
	}

}
