// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import type { Vec3 } from 'vec3';

export class ClientboundBlockEventPacket extends DripleafPacket {
	static readonly codec = packetCodec<ClientboundBlockEventPacket>({
		encode(writer: PacketWriter, value: ClientboundBlockEventPacket) {
		writer.writeBlockPos(value.position);
		writer.writeUnsignedByte(value.actionId);
		writer.writeUnsignedByte(value.actionParameter);
		writer.writeVarInt(value.blockType);
		},
		decode(reader: PacketReader): ClientboundBlockEventPacket {
		const position = reader.readBlockPos();
		const actionId = reader.readUnsignedByte();
		const actionParameter = reader.readUnsignedByte();
		const blockType = reader.readVarInt();
		return new ClientboundBlockEventPacket(position, actionId, actionParameter, blockType);
		},
	});

	constructor(
		public position: Vec3,
		public actionId: number,
		public actionParameter: number,
		public blockType: number // todo: registry
	) {
		super();
	}

}
