// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State, type Position } from '../../types';

export class ClientboundBlockUpdatePacket extends DripleafPacket {
	static readonly id = 0x08;
	static readonly state = State.Play;
	static readonly direction = Direction.Clientbound;

	override readonly id = ClientboundBlockUpdatePacket.id;
	override readonly state = ClientboundBlockUpdatePacket.state;
	override readonly direction = ClientboundBlockUpdatePacket.direction;

	constructor(
		public location: Position,
		public blockId: number
	) {
		super();
	}

	write(writer: PacketWriter) {
		writer.writePosition(this.location);
		writer.writeVarInt(this.blockId);
	}

	static read(reader: PacketReader): ClientboundBlockUpdatePacket {
		const location = reader.readPosition();
		const blockId = reader.readVarInt();
		return new ClientboundBlockUpdatePacket(location, blockId);
	}
}