// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { BlockEntityType } from '@dripleaf/registry';
import { BlockPos } from '@dripleaf/core';
import { BlockPosCodec } from '../../datatypes/BlockPos';
import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import type { UnnamedNbtTag } from '@dripleaf/nbt';

export class ClientboundBlockEntityDataPacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundBlockEntityDataPacket, {
		position: BlockPosCodec,
		type: Codecs.varIntEnum(BlockEntityType),
		data: Codecs.nbt,
	});

	constructor(
		public position: BlockPos,
		public type: BlockEntityType,
		public data: UnnamedNbtTag
	) {
		super();
	}
}