// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { BlockPos } from '@dripleaf/core';
import { BlockPosCodec } from '../../datatypes/BlockPos';
import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundBlockDestructionPacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundBlockDestructionPacket, {
		entityId: Codecs.varInt,
		position: BlockPosCodec,
		progress: Codecs.unsignedByte,
	});

	constructor(
		public entityId: number,
		public position: BlockPos,
		public progress: number
	) {
		super();
	}
}