// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import type { UnnamedNbtTag } from '@dripleaf/nbt';
import type { UUID } from 'node:crypto';

export enum BossEventAction {
	Add = 0,
	Remove = 1,
	UpdateProgress = 2,
	UpdateName = 3,
	UpdateStyle = 4,
	UpdateProperties = 5
}

export enum BossBarColor {
	Pink = 0,
	Blue = 1,
	Red = 2,
	Green = 3,
	Yellow = 4,
	Purple = 5,
	White = 6
}

export enum BossBarDividers {
	Progress = 0,
	Notched6 = 1,
	Notched10 = 2,
	Notched12 = 3,
	Notched20 = 4
}

export type BossEventAddOperation = {
	title: UnnamedNbtTag;
	health: number;
	color: BossBarColor;
	dividers: BossBarDividers;
	flags: number;
}

export type BossEventRemoveOperation = Record<string, never>;

export type BossEventUpdateProgressOperation = {
	health: number;
}

export type BossEventUpdateNameOperation = {
	title: UnnamedNbtTag;
}

export type BossEventUpdateStyleOperation = {
	color: BossBarColor;
	dividers: BossBarDividers;
}

export type BossEventUpdatePropertiesOperation = {
	flags: number;
}

export type BossEventOperation =
	| BossEventAddOperation
	| BossEventRemoveOperation
	| BossEventUpdateProgressOperation
	| BossEventUpdateNameOperation
	| BossEventUpdateStyleOperation
	| BossEventUpdatePropertiesOperation;

export class ClientboundBossEventPacket extends DripleafPacket {
	static readonly codec = packetCodec<ClientboundBossEventPacket>({
		encode(writer: PacketWriter, value: ClientboundBossEventPacket) {
		writer.writeUUID(value.uuid);
		writer.writeVarInt(value.action);
		switch (value.action) {
			case BossEventAction.Add: {
				const operation = value.operation as BossEventAddOperation;
				writer.writeNbt(operation.title);
				writer.writeFloat(operation.health);
				writer.writeVarInt(operation.color);
				writer.writeVarInt(operation.dividers);
				writer.writeUnsignedByte(operation.flags);
				return;
			}
			case BossEventAction.Remove:
				return;
			case BossEventAction.UpdateProgress:
				writer.writeFloat((value.operation as BossEventUpdateProgressOperation).health);
				return;
			case BossEventAction.UpdateName:
				writer.writeNbt((value.operation as BossEventUpdateNameOperation).title);
				return;
			case BossEventAction.UpdateStyle: {
				const operation = value.operation as BossEventUpdateStyleOperation;
				writer.writeVarInt(operation.color);
				writer.writeVarInt(operation.dividers);
				return;
			}
			case BossEventAction.UpdateProperties:
				writer.writeByte((value.operation as BossEventUpdatePropertiesOperation).flags);
				return;
			default:
				throw new Error(`Unknown boss event action: ${value.action}`);
		}
		},
		decode(reader: PacketReader): ClientboundBossEventPacket {
		const uuid = reader.readUUID();
		const action = reader.readVarInt() as BossEventAction;
		let operation: BossEventOperation;

		switch (action) {
			case BossEventAction.Add:
				operation = {
					title: reader.readNbt(),
					health: reader.readFloat(),
					color: reader.readVarInt() as BossBarColor,
					dividers: reader.readVarInt() as BossBarDividers,
					flags: reader.readUnsignedByte()
				};
				break;
			case BossEventAction.Remove:
				operation = {};
				break;
			case BossEventAction.UpdateProgress:
				operation = { health: reader.readFloat() };
				break;
			case BossEventAction.UpdateName:
				operation = { title: reader.readNbt() };
				break;
			case BossEventAction.UpdateStyle:
				operation = {
					color: reader.readVarInt() as BossBarColor,
					dividers: reader.readVarInt() as BossBarDividers
				};
				break;
			case BossEventAction.UpdateProperties:
				operation = { flags: reader.readUnsignedByte() };
				break;
			default:
				throw new Error(`Unknown boss event action: ${action}`);
		}

		return new ClientboundBossEventPacket(uuid, action, operation);
		},
	});

	constructor(
		public uuid: UUID,
		public action: BossEventAction,
		public operation: BossEventOperation
	) {
		super();
	}

}
