// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundBundleDelimiterPacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundBundleDelimiterPacket, {});

	constructor() {
		super();
	}
}

// note: i have no clue how this packet is going to be handled