// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { ChunkPos } from '../../datatypes/ChunkPos';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

type ChunkBiomeDataEntry = {
	chunkPos: ChunkPos
	data: Uint8Array;
};

export class ClientboundChunksBiomesPacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundChunksBiomesPacket, {
		chunkBiomeData: Codecs.array({
			encode(writer, value) {
				writer.writeByteArray(value.data);
			},
			decode(reader) {
				const chunkPos = ChunkPos.codec.decode(reader);
				const data = reader.readByteArray();
				return { chunkPos, data };
			},
		})
	});

	constructor(
		public chunkBiomeData: ChunkBiomeDataEntry[]
	) {
		super();
	}
}