// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

type ChunkBiomeDataEntry = {
	chunkZ: number;
	chunkX: number;
	data: Uint8Array;
};

export class ClientboundChunksBiomesPacket extends DripleafPacket {
	static readonly codec = packetCodec<ClientboundChunksBiomesPacket>({
		encode(writer: PacketWriter, value: ClientboundChunksBiomesPacket) {
		writer.writeArray(value.chunkBiomeData, (entry) => {
			writer.writeVarInt(entry.chunkZ);
			writer.writeVarInt(entry.chunkX);
			writer.writeByteArray(entry.data);
		});
		},
		decode(reader: PacketReader): ClientboundChunksBiomesPacket {
		const chunkBiomeData = reader.readArray(() => {
			const chunkZ = reader.readVarInt();
			const chunkX = reader.readVarInt();
			const data = reader.readByteArray();
			return { chunkZ, chunkX, data };
		});
		return new ClientboundChunksBiomesPacket(chunkBiomeData);
		},
	});

	constructor(
		public chunkBiomeData: ChunkBiomeDataEntry[]
	) {
		super();
	}

}
