// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundChunkBatchFinishedPacket extends DripleafPacket {
	static readonly codec = packetCodec<ClientboundChunkBatchFinishedPacket>({
		encode(writer: PacketWriter, value: ClientboundChunkBatchFinishedPacket) {
		writer.writeVarInt(value.batchSize);
		},
		decode(reader: PacketReader): ClientboundChunkBatchFinishedPacket {
		const batchSize = reader.readVarInt();
		return new ClientboundChunkBatchFinishedPacket(batchSize);
		},
	});

	constructor(
		public batchSize: number
	) {
		super();
	}

}
