// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export enum Difficulty {
	Peaceful = 0,
	Easy = 1,
	Normal = 2,
	Hard = 3
}

export class ClientboundChangeDifficultyPacket extends DripleafPacket {
	static readonly codec = packetCodec<ClientboundChangeDifficultyPacket>({
		encode(writer: PacketWriter, value: ClientboundChangeDifficultyPacket) {
		writer.writeUnsignedByte(value.difficulty);
		writer.writeBoolean(value.locked);
		},
		decode(reader: PacketReader): ClientboundChangeDifficultyPacket {
		const difficulty = reader.readUnsignedByte();
		const locked = reader.readBoolean();
		return new ClientboundChangeDifficultyPacket(difficulty, locked);
		},
	});

	constructor(
		public difficulty: Difficulty,
		public locked: boolean
	) {
		super();
	}

}
