// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State } from '../../types';

export enum Difficulty {
	Peaceful = 0,
	Easy = 1,
	Normal = 2,
	Hard = 3
}

export class ClientboundChangeDifficultyPacket extends DripleafPacket {
	static readonly id = 0x0a;
	static readonly state = State.Play;
	static readonly direction = Direction.Clientbound;

	override readonly id = ClientboundChangeDifficultyPacket.id;
	override readonly state = ClientboundChangeDifficultyPacket.state;
	override readonly direction = ClientboundChangeDifficultyPacket.direction;

	constructor(
		public difficulty: Difficulty,
		public locked: boolean
	) {
		super();
	}

	write(writer: PacketWriter) {
		writer.writeUnsignedByte(this.difficulty);
		writer.writeBoolean(this.locked);
	}

	static read(reader: PacketReader): ClientboundChangeDifficultyPacket {
		const difficulty = reader.readUnsignedByte();
		const locked = reader.readBoolean();
		return new ClientboundChangeDifficultyPacket(difficulty, locked);
	}
}