// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State } from '../../types';

export class ClientboundClearTitlesPacket extends DripleafPacket {
	static readonly id = 0x0e;
	static readonly state = State.Play;
	static readonly direction = Direction.Clientbound;

	override readonly id = ClientboundClearTitlesPacket.id;
	override readonly state = ClientboundClearTitlesPacket.state;
	override readonly direction = ClientboundClearTitlesPacket.direction;

	constructor(
		public reset: boolean
	) {
		super();
	}

	write(writer: PacketWriter) {
		writer.writeBoolean(this.reset);
	}

	static read(reader: PacketReader): ClientboundClearTitlesPacket {
		const reset = reader.readBoolean();
		return new ClientboundClearTitlesPacket(reset);
	}
}