// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundClearTitlesPacket extends DripleafPacket {
	static readonly codec = packetCodec<ClientboundClearTitlesPacket>({
		encode(writer: PacketWriter, value: ClientboundClearTitlesPacket) {
		writer.writeBoolean(value.reset);
		},
		decode(reader: PacketReader): ClientboundClearTitlesPacket {
		const reset = reader.readBoolean();
		return new ClientboundClearTitlesPacket(reset);
		},
	});

	constructor(
		public reset: boolean
	) {
		super();
	}

}
