// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundContainerSetSlotPacket extends DripleafPacket {
	static readonly codec = packetCodec<ClientboundContainerSetSlotPacket>({
		encode(writer: PacketWriter, value: ClientboundContainerSetSlotPacket) {
			throw new Error("TODO: implement codec encode");
		},
		decode(reader: PacketReader): ClientboundContainerSetSlotPacket {
			throw new Error("TODO: implement codec decode");
		},
	});

	constructor(
		public windowId: number,
		public stateId: number,
		public slot: number,
		public slotData: any // todo
	) {
		super();
	}

}
