// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import type { UnnamedNbtTag } from '@dripleaf/nbt';

type MatchEntry = {
	match: string;
	tooltip: UnnamedNbtTag | null;
}

export class ClientboundCommandSuggestionsPacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundCommandSuggestionsPacket, {
		transactionId: Codecs.varInt,
		start: Codecs.varInt,
		length: Codecs.varInt,
		matches: Codecs.array({
			encode(writer, value) {
				writer.writeString(value.match);
				writer.writePrefixedOptional(value.tooltip, (tooltip) => writer.writeNbt(tooltip));
			},
			decode(reader) {
				const match = reader.readString();
				const tooltip = reader.readPrefixedOptional(() => reader.readNbt());
				return { match, tooltip };
			},
		})
	});

	constructor(
		public transactionId: number,
		public start: number,
		public length: number,
		public matches: MatchEntry[]
	) {
		super();
	}
}