// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundContainerSetDataPacket extends DripleafPacket {
	static readonly codec = packetCodec<ClientboundContainerSetDataPacket>({
		encode(writer: PacketWriter, value: ClientboundContainerSetDataPacket) {
		writer.writeVarInt(value.windowId);
		writer.writeShort(value.property);
		writer.writeShort(value.value);
		},
		decode(reader: PacketReader): ClientboundContainerSetDataPacket {
		const windowId = reader.readVarInt();
		const property = reader.readShort();
		const value = reader.readShort();
		return new ClientboundContainerSetDataPacket(windowId, property, value);
		},
	});

	constructor(
		public windowId: number,
		public property: number,
		public value: number
	) {
		super();
	}

}
