// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundContainerClosePacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundContainerClosePacket, {
		windowId: Codecs.varInt,
	});

	constructor(
		public windowId: number
	) {
		super();
	}
}
