// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundContainerClosePacket extends DripleafPacket {
	static readonly codec = packetCodec<ClientboundContainerClosePacket>({
		encode(writer: PacketWriter, value: ClientboundContainerClosePacket) {
		writer.writeVarInt(value.windowId);
		},
		decode(reader: PacketReader): ClientboundContainerClosePacket {
		const windowId = reader.readVarInt();
		return new ClientboundContainerClosePacket(windowId);
		},
	});

	constructor(
		public windowId: number
	) {
		super();
	}

}
