// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State } from '../../types';

type Node = {
	flags: number;
	childrenCount: number;
	children: number[];

	redirectNode?: number | null; // flags & 0x08
	name?: string | null; // argument and literal nodes
	parserId?: number | null; // argument nodes
	properties?: unknown; // argument nodes, depends on parser
	suggestionType?: string | null; // flags & 0x10
}

export class ClientboundCommandsPacket extends DripleafPacket {
	static readonly id = 0x10;
	static readonly state = State.Play;
	static readonly direction = Direction.Clientbound;

	override readonly id = ClientboundCommandsPacket.id;
	override readonly state = ClientboundCommandsPacket.state;
	override readonly direction = ClientboundCommandsPacket.direction;

	constructor(
		public nodes: Node[],
		public rootIndex: number
	) {
		super();
	}

	write(writer: PacketWriter) {
		// todo
	}

	static read(reader: PacketReader): ClientboundCommandsPacket {
		// todo
	}
}