// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundContainerSetContentPacket extends DripleafPacket {
	static readonly codec = packetCodec<ClientboundContainerSetContentPacket>({
		encode(writer: PacketWriter, value: ClientboundContainerSetContentPacket) {
			throw new Error("TODO: implement codec encode");
		},
		decode(reader: PacketReader): ClientboundContainerSetContentPacket {
			throw new Error("TODO: implement codec decode");
		},
	});

	constructor(
		public windowId: number,
		public stateId: number,
		public slots: any[], // todo
		public carriedItem: any // todo
	) {
		super();
	}

}
