// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import type { ItemStack as InventoryItemStack } from '@dripleaf/inventory';
import { Codecs, type PacketReader, type PacketWriter } from '../../buffer';
import { ItemStackCodec } from '../common';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundContainerSetSlotPacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundContainerSetSlotPacket, {
		windowId: Codecs.varInt,
		stateId: Codecs.varInt,
		slot: Codecs.short,
		slotData: ItemStackCodec,
	});

	constructor(
		public windowId: number,
		public stateId: number,
		public slot: number,
		public slotData: InventoryItemStack,
	) {
		super();
	}
}
