// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

type Node = {
	flags: number;
	childrenCount: number;
	children: number[];

	redirectNode?: number | null; // flags & 0x08
	name?: string | null; // argument and literal nodes
	parserId?: number | null; // argument nodes
	properties?: unknown; // argument nodes, depends on parser
	suggestionType?: string | null; // flags & 0x10
}

export class ClientboundCommandsPacket extends DripleafPacket {
	static readonly codec = packetCodec<ClientboundCommandsPacket>({
		encode(writer: PacketWriter, value: ClientboundCommandsPacket) {
			throw new Error("TODO: implement codec encode");
		},
		decode(reader: PacketReader): ClientboundCommandsPacket {
			throw new Error("TODO: implement codec decode");
		},
	});

	constructor(
		public nodes: Node[],
		public rootIndex: number
	) {
		super();
	}

}
