// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export enum CustomChatCompletionsAction {
	Add = 0,
	Remove = 1,
	Set = 2,
}

export class ClientboundCustomChatCompletionsPacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundCustomChatCompletionsPacket, {
		action: Codecs.byteEnum(CustomChatCompletionsAction),
		entries: Codecs.array(Codecs.string()),
	});

	constructor(
		public action: CustomChatCompletionsAction,
		public entries: string[],
	) {
		super();
	}
}