// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State } from '../../types';
import { Vec3 } from 'vec3';

export class ClientboundDamageEventPacket extends DripleafPacket {
	static readonly id = 0x19;
	static readonly state = State.Play;
	static readonly direction = Direction.Clientbound;

	override readonly id = ClientboundDamageEventPacket.id;
	override readonly state = ClientboundDamageEventPacket.state;
	override readonly direction = ClientboundDamageEventPacket.direction;

	constructor(
		public entityId: number,
		public sourceTypeId: number,
		public sourceCauseId: number,
		public sourceDirectId: number,
		public sourcePosition: Vec3 | null,
	) {
		super();
	}

	write(writer: PacketWriter) {
		writer.writeVarInt(this.entityId);
		writer.writeVarInt(this.sourceTypeId);
		writer.writeVarInt(this.sourceCauseId);
		writer.writeVarInt(this.sourceDirectId);
		writer.writePrefixedOptional(this.sourcePosition, (pos) => {
			writer.writeVec3d(pos);
		});
	}

	static read(reader: PacketReader): ClientboundDamageEventPacket {
		const entityId = reader.readVarInt();
		const sourceTypeId = reader.readVarInt();
		const sourceCauseId = reader.readVarInt();
		const sourceDirectId = reader.readVarInt();
		const sourcePosition = reader.readPrefixedOptional(() => {
			return reader.readVec3d();
		});
		return new ClientboundDamageEventPacket(entityId, sourceTypeId, sourceCauseId, sourceDirectId, sourcePosition);
	}
}