// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import { Vec3 } from 'vec3';

export class ClientboundDamageEventPacket extends DripleafPacket {
	static readonly codec = packetCodec<ClientboundDamageEventPacket>({
		encode(writer: PacketWriter, value: ClientboundDamageEventPacket) {
		writer.writeVarInt(value.entityId);
		writer.writeVarInt(value.sourceTypeId);
		writer.writeVarInt(value.sourceCauseId);
		writer.writeVarInt(value.sourceDirectId);
		writer.writePrefixedOptional(value.sourcePosition, (pos) => {
			writer.writeVec3d(pos);
		});
		},
		decode(reader: PacketReader): ClientboundDamageEventPacket {
		const entityId = reader.readVarInt();
		const sourceTypeId = reader.readVarInt();
		const sourceCauseId = reader.readVarInt();
		const sourceDirectId = reader.readVarInt();
		const sourcePosition = reader.readPrefixedOptional(() => {
			return reader.readVec3d();
		});
		return new ClientboundDamageEventPacket(entityId, sourceTypeId, sourceCauseId, sourceDirectId, sourcePosition);
		},
	});

	constructor(
		public entityId: number,
		public sourceTypeId: number,
		public sourceCauseId: number,
		public sourceDirectId: number,
		public sourcePosition: Vec3 | null,
	) {
		super();
	}

}
