// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State } from '../../types';

export class ClientboundDeleteChatPacket extends DripleafPacket {
	static readonly id = 0x1f;
	static readonly state = State.Play;
	static readonly direction = Direction.Clientbound;

	override readonly id = ClientboundDeleteChatPacket.id;
	override readonly state = ClientboundDeleteChatPacket.state;
	override readonly direction = ClientboundDeleteChatPacket.direction;

	constructor(
		public messageId: number,
		public signature: Uint8Array | null
	) {
		super();
	}

	write(writer: PacketWriter) {
		writer.writeVarInt(this.messageId);
		if (this.signature) writer.writeByteArray(this.signature, 256);
	}

	static read(reader: PacketReader): ClientboundDeleteChatPacket {
		const messageId = reader.readVarInt();
		let signature: Uint8Array | null = null;
		if (reader.remaining == 256) signature = reader.readByteArray();
		return new ClientboundDeleteChatPacket(messageId, signature);
	}
}