// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import type { Vec3 } from 'vec3';

export class ClientboundDebugBlockValuePacket extends DripleafPacket {
	static readonly codec = packetCodec<ClientboundDebugBlockValuePacket>({
		encode(writer: PacketWriter, value: ClientboundDebugBlockValuePacket) {
		writer.writeBlockPos(value.location);
		throw new Error("todo");
		},
		decode(reader: PacketReader): ClientboundDebugBlockValuePacket {
		const location = reader.readBlockPos();
		throw new Error("todo");
		},
	});

	constructor(
		public location: Vec3,
		public update: any // todo
	) {
		super();
	}

}
