// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundDeleteChatPacket extends DripleafPacket {
	static readonly codec = packetCodec<ClientboundDeleteChatPacket>({
		encode(writer: PacketWriter, value: ClientboundDeleteChatPacket) {
		writer.writeVarInt(value.messageId);
		if (value.signature) writer.writeByteArray(value.signature, 256);
		},
		decode(reader: PacketReader): ClientboundDeleteChatPacket {
		const messageId = reader.readVarInt();
		let signature: Uint8Array | null = null;
		if (reader.remaining == 256) signature = reader.readByteArray();
		return new ClientboundDeleteChatPacket(messageId, signature);
		},
	});

	constructor(
		public messageId: number,
		public signature: Uint8Array | null
	) {
		super();
	}

}
