// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State } from '../../types';

export class ClientboundDebugSamplePacket extends DripleafPacket {
	static readonly id = 0x1e;
	static readonly state = State.Play;
	static readonly direction = Direction.Clientbound;

	override readonly id = ClientboundDebugSamplePacket.id;
	override readonly state = ClientboundDebugSamplePacket.state;
	override readonly direction = ClientboundDebugSamplePacket.direction;

	constructor(
		// todo
	) {
		super();
	}

	write(writer: PacketWriter) {
		// todo
	}

	static read(reader: PacketReader): ClientboundDebugSamplePacket {
		// todo
	}
}