// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State } from '../../types';
import type { Vec3 } from 'vec3';

export class ClientboundDebugBlockValuePacket extends DripleafPacket {
	static readonly id = 0x1a;
	static readonly state = State.Play;
	static readonly direction = Direction.Clientbound;

	override readonly id = ClientboundDebugBlockValuePacket.id;
	override readonly state = ClientboundDebugBlockValuePacket.state;
	override readonly direction = ClientboundDebugBlockValuePacket.direction;

	constructor(
		public location: Vec3,
		public update: any // todo
	) {
		super();
	}

	write(writer: PacketWriter) {
		writer.writeBlockPos(this.location);
		throw new Error("todo");
	}

	static read(reader: PacketReader): ClientboundDebugBlockValuePacket {
		const location = reader.readBlockPos();
		throw new Error("todo");
	}
}