// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State } from '../../types';

export class ClientboundDebugChunkValuePacket extends DripleafPacket {
	static readonly id = 0x1b;
	static readonly state = State.Play;
	static readonly direction = Direction.Clientbound;

	override readonly id = ClientboundDebugChunkValuePacket.id;
	override readonly state = ClientboundDebugChunkValuePacket.state;
	override readonly direction = ClientboundDebugChunkValuePacket.direction;

	constructor(
		public chunkZ: number,
		public chunkX: number,
		public update: any // todo
	) {
		super();
	}

	write(writer: PacketWriter) {
		// todo
	}

	static read(reader: PacketReader): ClientboundDebugChunkValuePacket {
		// todo
	}
}