// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundDebugEventPacket extends DripleafPacket {
	static readonly codec = packetCodec<ClientboundDebugEventPacket>({
		encode(writer: PacketWriter, value: ClientboundDebugEventPacket) {
			throw new Error("TODO: implement codec encode");
		},
		decode(reader: PacketReader): ClientboundDebugEventPacket {
			throw new Error("TODO: implement codec decode");
		},
	});

	constructor(
		public event: any // todo		
	) {
		super();
	}

}
