// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundDebugChunkValuePacket extends DripleafPacket {
	static readonly codec = packetCodec<ClientboundDebugChunkValuePacket>({
		encode(writer: PacketWriter, value: ClientboundDebugChunkValuePacket) {
			throw new Error("TODO: implement codec encode");
		},
		decode(reader: PacketReader): ClientboundDebugChunkValuePacket {
			throw new Error("TODO: implement codec decode");
		},
	});

	constructor(
		public chunkZ: number,
		public chunkX: number,
		public update: any // todo
	) {
		super();
	}

}
