// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { DebugSubscription } from '@dripleaf/registry';
import { ChunkPos } from '@dripleaf/core';
import { ChunkPosCodec } from '../../datatypes/ChunkPos';
import { codec, Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import type { DebugUpdatePayload } from '../common';

export class ClientboundDebugChunkValuePacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundDebugChunkValuePacket, {
		chunkPos: ChunkPosCodec,
		update: codec({
			encode(writer, value) {
				Codecs.varIntEnum(DebugSubscription).encode(writer, value.subscription)
				writer.writeBytes(value.payload)
			},
			decode(reader) {
				return {
					subscription: Codecs.varIntEnum(DebugSubscription).decode(reader),
					payload: reader.readRemaining(),
				}
			}
		})
	});

	constructor(
		public chunkPos: ChunkPos,
		public update: DebugUpdatePayload,
	) {
		super();
	}
}
