// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import type { UnnamedNbtTag } from '@dripleaf/nbt';

export class ClientboundDisguisedChatPacket extends DripleafPacket {
	static readonly codec = packetCodec<ClientboundDisguisedChatPacket>({
		encode(writer: PacketWriter, value: ClientboundDisguisedChatPacket) {
		writer.writeNbt(value.message);
		writer.writeString(value.chatType);
		writer.writeNbt(value.senderName);
		writer.writePrefixedOptional(value.targetName, (targetName) => writer.writeNbt(targetName));
		},
		decode(reader: PacketReader): ClientboundDisguisedChatPacket {
		const message = reader.readNbt();
		const chatType = reader.readString();
		const senderName = reader.readNbt();
		const targetName = reader.readPrefixedOptional(() => reader.readNbt());
		return new ClientboundDisguisedChatPacket(message, chatType, senderName, targetName);
		},
	});

	constructor(
		public message: UnnamedNbtTag,
		public chatType: string, // Either the type of chat in the minecraft:chat_type registry, defined by the Registry Data packet, or an inline definition.
		public senderName: UnnamedNbtTag,
		public targetName: UnnamedNbtTag | null
	) {
		super();
	}

}
