// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State } from '../../types';
import type { UnnamedNbtTag } from '@dripleaf/nbt';

export class ClientboundDisguisedChatPacket extends DripleafPacket {
	static readonly id = 0x21;
	static readonly state = State.Play;
	static readonly direction = Direction.Clientbound;

	override readonly id = ClientboundDisguisedChatPacket.id;
	override readonly state = ClientboundDisguisedChatPacket.state;
	override readonly direction = ClientboundDisguisedChatPacket.direction;

	constructor(
		public message: UnnamedNbtTag,
		public chatType: string, // Either the type of chat in the minecraft:chat_type registry, defined by the Registry Data packet, or an inline definition.
		public senderName: UnnamedNbtTag,
		public targetName: UnnamedNbtTag | null
	) {
		super();
	}

	write(writer: PacketWriter) {
		writer.writeNbt(this.message);
		writer.writeString(this.chatType);
		writer.writeNbt(this.senderName);
		writer.writePrefixedOptional(this.targetName, (targetName) => writer.writeNbt(targetName));
	}

	static read(reader: PacketReader): ClientboundDisguisedChatPacket {
		const message = reader.readNbt();
		const chatType = reader.readString();
		const senderName = reader.readNbt();
		const targetName = reader.readPrefixedOptional(() => reader.readNbt());
		return new ClientboundDisguisedChatPacket(message, chatType, senderName, targetName);
	}
}