// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundEntityEventPacket extends DripleafPacket {
	static readonly codec = packetCodec<ClientboundEntityEventPacket>({
		encode(writer: PacketWriter, value: ClientboundEntityEventPacket) {
		writer.writeVarInt(value.entityId);
		writer.writeByte(value.entityStatus);
		},
		decode(reader: PacketReader): ClientboundEntityEventPacket {
		const entityId = reader.readVarInt();
		const entityStatus = reader.readByte();
		return new ClientboundEntityEventPacket(entityId, entityStatus);
		},
	});

	constructor(
		public entityId: number,
		public entityStatus: number // todo: enum
	) {
		super();
	}

}
