// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State } from '../../types';

export class ClientboundEntityEventPacket extends DripleafPacket {
	static readonly id = 0x22;
	static readonly state = State.Play;
	static readonly direction = Direction.Clientbound;

	override readonly id = ClientboundEntityEventPacket.id;
	override readonly state = ClientboundEntityEventPacket.state;
	override readonly direction = ClientboundEntityEventPacket.direction;

	constructor(
		public entityId: number,
		public entityStatus: number // todo: enum
	) {
		super();
	}

	write(writer: PacketWriter) {
		writer.writeVarInt(this.entityId);
		writer.writeByte(this.entityStatus);
	}

	static read(reader: PacketReader): ClientboundEntityEventPacket {
		const entityId = reader.readVarInt();
		const entityStatus = reader.readByte();
		return new ClientboundEntityEventPacket(entityId, entityStatus);
	}
}