// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PositionMoveRotation } from '@dripleaf/core';
import { PositionMoveRotationCodec } from '../../datatypes/PositionMoveRotation';
import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundEntityPositionSyncPacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundEntityPositionSyncPacket, {
		entityId: Codecs.varInt,
		values: PositionMoveRotationCodec,
		onGround: Codecs.bool,
	});

	constructor(
		public entityId: number,
		public values: PositionMoveRotation,
		public onGround: boolean
	) {
		super();
	}
}