// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State } from '../../types';

export class ClientboundEntityPositionSyncPacket extends DripleafPacket {
	static readonly id = 0x23;
	static readonly state = State.Play;
	static readonly direction = Direction.Clientbound;

	override readonly id = ClientboundEntityPositionSyncPacket.id;
	override readonly state = ClientboundEntityPositionSyncPacket.state;
	override readonly direction = ClientboundEntityPositionSyncPacket.direction;

	constructor(
		public entityId: number,
		public x: number,
		public y: number,
		public z: number,
		public velocityX: number,
		public velocityY: number,
		public velocityZ: number,
		public yaw: number,
		public pitch: number,
		public onGround: boolean
	) {
		super();
	}

	write(writer: PacketWriter) {
		writer.writeVarInt(this.entityId);
		writer.writeDouble(this.x);
		writer.writeDouble(this.y);
		writer.writeDouble(this.z);
		writer.writeDouble(this.velocityX);
		writer.writeDouble(this.velocityY);
		writer.writeDouble(this.velocityZ);
		writer.writeFloat(this.yaw);
		writer.writeFloat(this.pitch);
		writer.writeBoolean(this.onGround);
	}

	static read(reader: PacketReader): ClientboundEntityPositionSyncPacket {
		const entityId = reader.readVarInt();
		const x = reader.readDouble();
		const y = reader.readDouble();
		const z = reader.readDouble();
		const velocityX = reader.readDouble();
		const velocityY = reader.readDouble();
		const velocityZ = reader.readDouble();
		const yaw = reader.readFloat();
		const pitch = reader.readFloat();
		const onGround = reader.readBoolean();
		return new ClientboundEntityPositionSyncPacket(entityId, x, y, z, velocityX, velocityY, velocityZ, yaw, pitch, onGround);
	}
}