// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

type SoundEvent = {
	soundName: string,
	hasFixedRange: boolean,
	fixedRange?: number,
};

type BlockParticleAlternativeEntry = {
	particleId: number,
	particleData: any, // todo
	scaling: number,
	speed: number,
	weight: number,
}

export class ClientboundExplodePacket extends DripleafPacket {
	static readonly codec = packetCodec<ClientboundExplodePacket>({
		encode(writer: PacketWriter, value: ClientboundExplodePacket) {
			throw new Error("TODO: implement codec encode");
		},
		decode(reader: PacketReader): ClientboundExplodePacket {
			throw new Error("TODO: implement codec decode");
		},
	});

	constructor(
		public x: number,
		public y: number,
		public z: number,
		public radius: number,
		public blockCount: number,
		public playerDeltaVelocity: { x: number, y: number, z: number } | null,
		public explosionParticleId: number,
		public explosionParticleData: any, // todo
		public explosionSound: SoundEvent | number,
		public blockParticleAlternatives: BlockParticleAlternativeEntry[]
	) {
		super();
	}

}
