// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State } from '../../types';

export class ClientboundExplodePacket extends DripleafPacket {
	static readonly id = 0x24;
	static readonly state = State.Play;
	static readonly direction = Direction.Clientbound;

	override readonly id = ClientboundExplodePacket.id;
	override readonly state = ClientboundExplodePacket.state;
	override readonly direction = ClientboundExplodePacket.direction;

	constructor(
		// todo
	) {
		super();
	}

	write(writer: PacketWriter) {
		// todo
	}

	static read(reader: PacketReader): ClientboundExplodePacket {
		// todo
	}
}