// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { ChunkPos } from '@dripleaf/core';
import { ChunkPosCodec } from '../../datatypes/ChunkPos';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundForgetLevelChunkPacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundForgetLevelChunkPacket, {
		chunkPos: ChunkPosCodec,
	});

	constructor(
		public chunkPos: ChunkPos,
	) {
		super();
	}
}