// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundForgetLevelChunkPacket extends DripleafPacket {
	static readonly codec = packetCodec<ClientboundForgetLevelChunkPacket>({
		encode(writer: PacketWriter, value: ClientboundForgetLevelChunkPacket) {
		writer.writeInt(value.chunkZ);
		writer.writeInt(value.chunkX);
		},
		decode(reader: PacketReader): ClientboundForgetLevelChunkPacket {
		const chunkZ = reader.readInt();
		const chunkX = reader.readInt();
		return new ClientboundForgetLevelChunkPacket(chunkZ, chunkX);
		},
	});

	constructor(
		public chunkZ: number,
		public chunkX: number
	) {
		super();
	}

}
