// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { GameRule } from '@dripleaf/registry';
import { Codecs, type PacketReader, type PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundGameRuleValuesPacket extends DripleafPacket {
	static readonly codec = packetCodec({
		encode(writer: PacketWriter, value: ClientboundGameRuleValuesPacket) {
			const entries = Object.entries(value.values) as [string, string][]
			writer.writeArray(entries, ([rule, entry]) => {
				Codecs.varIntEnum(GameRule).encode(writer, rule as GameRule)
				writer.writeString(entry)
			})
		},
		decode(reader: PacketReader): ClientboundGameRuleValuesPacket {
			const values: Partial<Record<GameRule, string>> = {}
			for (const [rule, entry] of reader.readArray(() => [Codecs.varIntEnum(GameRule).decode(reader), reader.readString()] as const))
				values[rule] = entry
			return new ClientboundGameRuleValuesPacket(values)
		},
	});

	constructor(
		public values: Partial<Record<GameRule, string>>,
	) {
		super();
	}

}
