// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import type { Vec3 } from 'vec3';

export class ClientboundGameTestHighlightPosPacket extends DripleafPacket {
	static readonly codec = packetCodec<ClientboundGameTestHighlightPosPacket>({
		encode(writer: PacketWriter, value: ClientboundGameTestHighlightPosPacket) {
		writer.writeBlockPos(value.absolutePosition);
		writer.writeBlockPos(value.relativePosition);
		},
		decode(reader: PacketReader): ClientboundGameTestHighlightPosPacket {
		const absolutePosition = reader.readBlockPos();
		const relativePosition = reader.readBlockPos();
		return new ClientboundGameTestHighlightPosPacket(absolutePosition, relativePosition);
		},
	});

	constructor(
		public absolutePosition: Vec3,
		public relativePosition: Vec3
	) {
		super();
	}

}
