// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State } from '../../types';
import type { Vec3 } from 'vec3';

export class ClientboundGameTestHighlightPosPacket extends DripleafPacket {
	static readonly id = 0x28;
	static readonly state = State.Play;
	static readonly direction = Direction.Clientbound;

	override readonly id = ClientboundGameTestHighlightPosPacket.id;
	override readonly state = ClientboundGameTestHighlightPosPacket.state;
	override readonly direction = ClientboundGameTestHighlightPosPacket.direction;

	constructor(
		public absolutePosition: Vec3,
		public relativePosition: Vec3
	) {
		super();
	}

	write(writer: PacketWriter) {
		writer.writeBlockPos(this.absolutePosition);
		writer.writeBlockPos(this.relativePosition);
	}

	static read(reader: PacketReader): ClientboundGameTestHighlightPosPacket {
		const absolutePosition = reader.readBlockPos();
		const relativePosition = reader.readBlockPos();
		return new ClientboundGameTestHighlightPosPacket(absolutePosition, relativePosition);
	}
}