// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

enum GameEvent {
	InvalidBed = 0,
	StartRaining = 1,
	StopRaining = 2,
	ChangeGameMode = 3,
	WinGame = 4,
	DemoteToSpectator = 5,
	ArrowHitPlayer = 6,
	RainLevelChange = 7,
	ThunderLevelChange = 8,
	PufferfishSting = 9,
	ElderGuardianMobAppearance = 10,
	EnableRespawnScreen = 11,
	LimitedCrafting = 12,
	WaitForLevelChunks = 13,
}

export class ClientboundGameEventPacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundGameEventPacket, {
		event: Codecs.unsignedByteEnum(GameEvent),
		value: Codecs.float,
	});

	constructor(
		public event: GameEvent,
		public value: number
	) {
		super();
	}
}