// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State } from '../../types';

export class ClientboundHurtAnimationPacket extends DripleafPacket {
	static readonly id = 0x2a;
	static readonly state = State.Play;
	static readonly direction = Direction.Clientbound;

	override readonly id = ClientboundHurtAnimationPacket.id;
	override readonly state = ClientboundHurtAnimationPacket.state;
	override readonly direction = ClientboundHurtAnimationPacket.direction;

	constructor(
		public entityId: number,
		public yaw: number
	) {
		super();
	}

	write(writer: PacketWriter) {
		writer.writeVarInt(this.entityId);
		writer.writeFloat(this.yaw);
	}

	static read(reader: PacketReader): ClientboundHurtAnimationPacket {
		const entityId = reader.readVarInt();
		const yaw = reader.readFloat();
		return new ClientboundHurtAnimationPacket(entityId, yaw);
	}
}