// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Direction, State } from '../../types';
import { GlowstonePacket } from '../../packet';
import { PacketReader, PacketWriter } from '../../buffer';

class ClientboundHurtAnimationPacket extends GlowstonePacket {
	override id = 0x2a;
	override state = State.Play;
	override direction = Direction.Clientbound;

	constructor(
		// todo
	) {
		super();
	}

	serialize() {
		// todo
	}

	static override deserialize(bytes: Uint8Array): ClientboundHurtAnimationPacket {
		// todo
	}
}

export { ClientboundHurtAnimationPacket };