// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundInitializeBorderPacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundInitializeBorderPacket, {
		x: Codecs.double,
		z: Codecs.double,
		oldDiameter: Codecs.double,
		newDiameter: Codecs.double,
		speed: Codecs.varLong,
		portalTeleportBoundary: Codecs.varInt,
		warningBlocks: Codecs.varInt,
		warningTime: Codecs.varInt,
	});

	constructor(
		public x: number,
		public z: number,
		public oldDiameter: number,
		public newDiameter: number,
		public speed: bigint,
		public portalTeleportBoundary: number,
		public warningBlocks: number,
		public warningTime: number
	) {
		super();
	}
}