// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State } from '../../types';

export class ClientboundInitializeBorderPacket extends DripleafPacket {
	static readonly id = 0x2b;
	static readonly state = State.Play;
	static readonly direction = Direction.Clientbound;

	override readonly id = ClientboundInitializeBorderPacket.id;
	override readonly state = ClientboundInitializeBorderPacket.state;
	override readonly direction = ClientboundInitializeBorderPacket.direction;

	constructor(
		public x: number,
		public z: number,
		public oldDiameter: number,
		public newDiameter: number,
		public speed: bigint,
		public portalTeleportBoundary: number,
		public warningBlocks: number,
		public warningTime: number
	) {
		super();
	}

	write(writer: PacketWriter) {
		writer.writeDouble(this.x);
		writer.writeDouble(this.z);
		writer.writeDouble(this.oldDiameter);
		writer.writeDouble(this.newDiameter);
		writer.writeVarLong(this.speed);
		writer.writeVarInt(this.portalTeleportBoundary);
		writer.writeVarInt(this.warningBlocks);
		writer.writeVarInt(this.warningTime);
	}

	static read(reader: PacketReader): ClientboundInitializeBorderPacket {
		const x = reader.readDouble();
		const z = reader.readDouble();
		const oldDiameter = reader.readDouble();
		const newDiameter = reader.readDouble();
		const speed = reader.readVarLong();
		const portalTeleportBoundary = reader.readVarInt();
		const warningBlocks = reader.readVarInt();
		const warningTime = reader.readVarInt();
		return new ClientboundInitializeBorderPacket(x, z, oldDiameter, newDiameter, speed, portalTeleportBoundary, warningBlocks, warningTime);
	}
}