// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundInitializeBorderPacket extends DripleafPacket {
	static readonly codec = packetCodec<ClientboundInitializeBorderPacket>({
		encode(writer: PacketWriter, value: ClientboundInitializeBorderPacket) {
		writer.writeDouble(value.x);
		writer.writeDouble(value.z);
		writer.writeDouble(value.oldDiameter);
		writer.writeDouble(value.newDiameter);
		writer.writeVarLong(value.speed);
		writer.writeVarInt(value.portalTeleportBoundary);
		writer.writeVarInt(value.warningBlocks);
		writer.writeVarInt(value.warningTime);
		},
		decode(reader: PacketReader): ClientboundInitializeBorderPacket {
		const x = reader.readDouble();
		const z = reader.readDouble();
		const oldDiameter = reader.readDouble();
		const newDiameter = reader.readDouble();
		const speed = reader.readVarLong();
		const portalTeleportBoundary = reader.readVarInt();
		const warningBlocks = reader.readVarInt();
		const warningTime = reader.readVarInt();
		return new ClientboundInitializeBorderPacket(x, z, oldDiameter, newDiameter, speed, portalTeleportBoundary, warningBlocks, warningTime);
		},
	});

	constructor(
		public x: number,
		public z: number,
		public oldDiameter: number,
		public newDiameter: number,
		public speed: bigint,
		public portalTeleportBoundary: number,
		public warningBlocks: number,
		public warningTime: number
	) {
		super();
	}

}
