// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State } from '../../types';
import type { Vec3 } from 'vec3';

export class ClientboundLevelEventPacket extends DripleafPacket {
	static readonly id = 0x2e;
	static readonly state = State.Play;
	static readonly direction = Direction.Clientbound;

	override readonly id = ClientboundLevelEventPacket.id;
	override readonly state = ClientboundLevelEventPacket.state;
	override readonly direction = ClientboundLevelEventPacket.direction;

	constructor(
		public type: number,
		public position: Vec3,
		public data: number,
		public globalEvent: boolean
	) {
		super();
	}

	write(writer: PacketWriter) {
		writer.writeInt(this.type);
		writer.writeBlockPos(this.position);
		writer.writeInt(this.data);
		writer.writeBoolean(this.globalEvent);
	}

	static read(reader: PacketReader): ClientboundLevelEventPacket {
		const type = reader.readInt();
		const position = reader.readBlockPos();
		const data = reader.readInt();
		const globalEvent = reader.readBoolean();
		return new ClientboundLevelEventPacket(type, position, data, globalEvent);
	}
}