// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import type { Vec3 } from 'vec3';

export class ClientboundLevelEventPacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundLevelEventPacket, {
		type: Codecs.int,
		position: Codecs.blockPos,
		data: Codecs.int,
		globalEvent: Codecs.bool,
	});

	constructor(
		public type: number,
		public position: Vec3,
		public data: number,
		public globalEvent: boolean
	) {
		super();
	}
}