// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import type { UnnamedNbtTag } from '@dripleaf/nbt';
import { BlockEntityType } from '@dripleaf/registry';
import { Codecs, type PacketReader, type PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export type ChunkHeightmapEntry = {
	type: number
	data: bigint[]
}

export type ChunkBlockEntityInfo = {
	packedXZ: number
	y: number
	type: BlockEntityType
	tag: UnnamedNbtTag | null
}

export type ClientboundLevelChunkPacketData = {
	heightmaps: ChunkHeightmapEntry[]
	data: Uint8Array
	blockEntities: ChunkBlockEntityInfo[]
}

export type ClientboundLightUpdatePacketData = {
	skyYMask: bigint[]
	blockYMask: bigint[]
	emptySkyYMask: bigint[]
	emptyBlockYMask: bigint[]
	skyUpdates: Uint8Array[]
	blockUpdates: Uint8Array[]
}

const chunkDataCodec = {
	encode(writer: PacketWriter, value: ClientboundLevelChunkPacketData) {
		writer.writeArray(value.heightmaps, entry => {
			writer.writeVarInt(entry.type)
			writer.writeArray(entry.data, word => writer.writeLong(word))
		})
		writer.writeVarInt(value.data.length)
		writer.writeBytes(value.data)
		writer.writeArray(value.blockEntities, blockEntity => {
			writer.writeByte(blockEntity.packedXZ, 0, 255)
			writer.writeShort(blockEntity.y)
			Codecs.varIntEnum(BlockEntityType).encode(writer, blockEntity.type)
			writer.writeOptionalNbt(blockEntity.tag)
		})
	},
	decode(reader: PacketReader): ClientboundLevelChunkPacketData {
		const heightmaps = reader.readArray(() => ({
			type: reader.readVarInt(),
			data: reader.readArray(() => reader.readLong()),
		}))
		const data = reader.readBytes(reader.readVarInt())
		const blockEntities = reader.readArray(() => ({
			packedXZ: reader.readUnsignedByte(),
			y: reader.readShort(),
			type: Codecs.varIntEnum(BlockEntityType).decode(reader),
			tag: reader.readOptionalNbt(),
		}))
		return { heightmaps, data, blockEntities }
	},
}

const lightDataCodec = {
	encode(writer: PacketWriter, value: ClientboundLightUpdatePacketData) {
		writer.writeBitSet(value.skyYMask)
		writer.writeBitSet(value.blockYMask)
		writer.writeBitSet(value.emptySkyYMask)
		writer.writeBitSet(value.emptyBlockYMask)
		writer.writeArray(value.skyUpdates, update => writer.writeByteArray(update, 2048))
		writer.writeArray(value.blockUpdates, update => writer.writeByteArray(update, 2048))
	},
	decode(reader: PacketReader): ClientboundLightUpdatePacketData {
		return {
			skyYMask: reader.readBitSet(),
			blockYMask: reader.readBitSet(),
			emptySkyYMask: reader.readBitSet(),
			emptyBlockYMask: reader.readBitSet(),
			skyUpdates: reader.readArray(() => reader.readByteArray(2048)),
			blockUpdates: reader.readArray(() => reader.readByteArray(2048)),
		}
	},
}

export class ClientboundLevelChunkWithLightPacket extends DripleafPacket {
	static readonly codec = packetCodec({
		encode(writer: PacketWriter, value: ClientboundLevelChunkWithLightPacket) {
			writer.writeInt(value.x)
			writer.writeInt(value.z)
			chunkDataCodec.encode(writer, value.chunkData)
			lightDataCodec.encode(writer, value.lightData)
		},
		decode(reader: PacketReader): ClientboundLevelChunkWithLightPacket {
			return new ClientboundLevelChunkWithLightPacket(
				reader.readInt(),
				reader.readInt(),
				chunkDataCodec.decode(reader),
				lightDataCodec.decode(reader),
			)
		},
	});

	constructor(
		public x: number,
		public z: number,
		public chunkData: ClientboundLevelChunkPacketData,
		public lightData: ClientboundLightUpdatePacketData,
	) {
		super();
	}
}
