// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import type { Vec3 } from 'vec3';

export class ClientboundLevelEventPacket extends DripleafPacket {
	static readonly codec = packetCodec<ClientboundLevelEventPacket>({
		encode(writer: PacketWriter, value: ClientboundLevelEventPacket) {
		writer.writeInt(value.type);
		writer.writeBlockPos(value.position);
		writer.writeInt(value.data);
		writer.writeBoolean(value.globalEvent);
		},
		decode(reader: PacketReader): ClientboundLevelEventPacket {
		const type = reader.readInt();
		const position = reader.readBlockPos();
		const data = reader.readInt();
		const globalEvent = reader.readBoolean();
		return new ClientboundLevelEventPacket(type, position, data, globalEvent);
		},
	});

	constructor(
		public type: number,
		public position: Vec3,
		public data: number,
		public globalEvent: boolean
	) {
		super();
	}

}
