// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundLightUpdatePacket extends DripleafPacket {
	static readonly codec = packetCodec<ClientboundLightUpdatePacket>({
		encode(writer: PacketWriter, value: ClientboundLightUpdatePacket) {
		writer.writeVarInt(value.x);
		writer.writeVarInt(value.z);
		},
		decode(reader: PacketReader): ClientboundLightUpdatePacket {
		const x = reader.readVarInt();
		const z = reader.readVarInt();
		return new ClientboundLightUpdatePacket(x, z, null);
		},
	});

	constructor(
		public x: number,
		public z: number,
		public lightData: any // todo
	) {
		super();
	}

}
