// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundLowDiskSpaceWarningPacket extends DripleafPacket {
	static readonly codec = packetCodec<ClientboundLowDiskSpaceWarningPacket>({
		encode(writer: PacketWriter, value: ClientboundLowDiskSpaceWarningPacket) {
		void writer;
		},
		decode(reader: PacketReader): ClientboundLowDiskSpaceWarningPacket {
		void reader;
		return new ClientboundLowDiskSpaceWarningPacket();
		},
	});

	constructor() {
		super();
	}

}
