// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State } from '../../types';
import { CommonPlayerSpawnInfo } from '../../datatypes/CommonPlayerSpawnInfo';

export class ClientboundLoginPacket extends DripleafPacket {
	static readonly id = 0x31;
	static readonly state = State.Play;
	static readonly direction = Direction.Clientbound;

	override readonly id = ClientboundLoginPacket.id;
	override readonly state = ClientboundLoginPacket.state;
	override readonly direction = ClientboundLoginPacket.direction;

	constructor(
		public entityId: number,
		public isHardcore: boolean,
		public dimensions: string[],
		public maxPlayers: number,
		public viewDistance: number,
		public simulationDistance: number,
		public reducedDebugInfo: boolean,
		public enableRespawnScreen: boolean,
		public doLimitedCrafting: boolean,
		public commonPlayerSpawnInfo: CommonPlayerSpawnInfo,
		public portalCooldown: number,
		public seaLevel: number
	) {
		super();
	}

	write(writer: PacketWriter) {
		writer.writeInt(this.entityId);
		writer.writeBoolean(this.isHardcore);
		writer.writeArray(this.dimensions, (dimension) => writer.writeString(dimension));
		writer.writeVarInt(this.maxPlayers);
		writer.writeVarInt(this.viewDistance);
		writer.writeVarInt(this.simulationDistance);
		writer.writeBoolean(this.reducedDebugInfo);
		writer.writeBoolean(this.enableRespawnScreen);
		writer.writeBoolean(this.doLimitedCrafting);
		this.commonPlayerSpawnInfo.write(writer);
		writer.writeVarInt(this.portalCooldown);
		writer.writeVarInt(this.seaLevel);
	}

	static read(reader: PacketReader): ClientboundLoginPacket {
		const entityId = reader.readInt();
		const isHardcore = reader.readBoolean();
		const dimensions = reader.readArray(() => reader.readString());
		const maxPlayers = reader.readVarInt();
		const viewDistance = reader.readVarInt();
		const simulationDistance = reader.readVarInt();
		const reducedDebugInfo = reader.readBoolean();
		const enableRespawnScreen = reader.readBoolean();
		const doLimitedCrafting = reader.readBoolean();
		const commonPlayerSpawnInfo = CommonPlayerSpawnInfo.read(reader);
		const portalCooldown = reader.readVarInt();
		const seaLevel = reader.readVarInt();
		return new ClientboundLoginPacket(entityId, isHardcore, dimensions, maxPlayers, viewDistance, simulationDistance, reducedDebugInfo, enableRespawnScreen, doLimitedCrafting, commonPlayerSpawnInfo, portalCooldown, seaLevel);
	}
}