// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State } from '../../types';

type MerchantOffer = {
	// todo
}

export class ClientboundMerchantOffersPacket extends DripleafPacket {
	static readonly id = 0x34;
	static readonly state = State.Play;
	static readonly direction = Direction.Clientbound;

	override readonly id = ClientboundMerchantOffersPacket.id;
	override readonly state = ClientboundMerchantOffersPacket.state;
	override readonly direction = ClientboundMerchantOffersPacket.direction;

	constructor(
		public windowId: number,
		public offers: unknown, // todo
		public villagerLevel: number,
		public villagerXp: number,
		public showProgress: boolean,
		public canRestock: boolean
	) {
		super();
	}

	write(writer: PacketWriter) {
		writer.writeVarInt(this.windowId);

	}

	static read(reader: PacketReader): ClientboundMerchantOffersPacket {
		// todo
	}
}