// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import type { ItemStack as InventoryItemStack } from '@dripleaf/inventory';
import { ItemType } from '@dripleaf/registry';
import { Codecs, type PacketReader, type PacketWriter } from '../../buffer';
import { ItemStackCodec } from '../common';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

type MerchantOffer = {
	baseCostA: ItemCost
	result: InventoryItemStack
	costB: ItemCost | null
	outOfStock: boolean
	uses: number
	maxUses: number
	xp: number
	specialPriceDiff: number
	priceMultiplier: number
	demand: number
}

type ItemCost = {
	item: ItemType
	count: number
	components: ExactComponentPredicate
}

type ExactComponentPredicate = {
	expected: []
}

const itemCostCodec = {
	encode(writer: PacketWriter, value: ItemCost) {
		Codecs.varIntEnum(ItemType).encode(writer, value.item)
		writer.writeVarInt(value.count)
		writer.writeVarInt(value.components.expected.length)
	},
	decode(reader: PacketReader): ItemCost {
		const item = Codecs.varIntEnum(ItemType).decode(reader)
		const count = reader.readVarInt()
		const expectedCount = reader.readVarInt()
		if (expectedCount !== 0)
			throw new Error(`ItemCost exact component predicates not implemented yet: ${expectedCount}`)
		return { item, count, components: { expected: [] } }
	},
}

const merchantOfferCodec = {
	encode(writer: PacketWriter, value: MerchantOffer) {
		itemCostCodec.encode(writer, value.baseCostA)
		ItemStackCodec.encode(writer, value.result)
		writer.writePrefixedOptional(value.costB, cost => itemCostCodec.encode(writer, cost))
		writer.writeBoolean(value.outOfStock)
		writer.writeInt(value.uses)
		writer.writeInt(value.maxUses)
		writer.writeInt(value.xp)
		writer.writeInt(value.specialPriceDiff)
		writer.writeFloat(value.priceMultiplier)
		writer.writeInt(value.demand)
	},
	decode(reader: PacketReader): MerchantOffer {
		return {
			baseCostA: itemCostCodec.decode(reader),
			result: ItemStackCodec.decode(reader),
			costB: reader.readPrefixedOptional(() => itemCostCodec.decode(reader)),
			outOfStock: reader.readBoolean(),
			uses: reader.readInt(),
			maxUses: reader.readInt(),
			xp: reader.readInt(),
			specialPriceDiff: reader.readInt(),
			priceMultiplier: reader.readFloat(),
			demand: reader.readInt(),
		}
	},
}

export class ClientboundMerchantOffersPacket extends DripleafPacket {
	static readonly codec = packetCodec({
		encode(writer: PacketWriter, value: ClientboundMerchantOffersPacket) {
			writer.writeVarInt(value.windowId)
			writer.writeArray(value.offers, offer => merchantOfferCodec.encode(writer, offer))
			writer.writeVarInt(value.villagerLevel)
			writer.writeVarInt(value.villagerXp)
			writer.writeBoolean(value.showProgress)
			writer.writeBoolean(value.canRestock)
		},
		decode(reader: PacketReader): ClientboundMerchantOffersPacket {
			return new ClientboundMerchantOffersPacket(
				reader.readVarInt(),
				reader.readArray(() => merchantOfferCodec.decode(reader)),
				reader.readVarInt(),
				reader.readVarInt(),
				reader.readBoolean(),
				reader.readBoolean(),
			)
		},
	});

	constructor(
		public windowId: number,
		public offers: MerchantOffer[],
		public villagerLevel: number,
		public villagerXp: number,
		public showProgress: boolean,
		public canRestock: boolean
	) {
		super();
	}

}
