// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

type MerchantOffer = {
	// todo
}

export class ClientboundMerchantOffersPacket extends DripleafPacket {
	static readonly codec = packetCodec<ClientboundMerchantOffersPacket>({
		encode(writer: PacketWriter, value: ClientboundMerchantOffersPacket) {
		writer.writeVarInt(value.windowId);

		},
		decode(reader: PacketReader): ClientboundMerchantOffersPacket {
			throw new Error("TODO: implement codec decode");
		},
	});

	constructor(
		public windowId: number,
		public offers: unknown, // todo
		public villagerLevel: number,
		public villagerXp: number,
		public showProgress: boolean,
		public canRestock: boolean
	) {
		super();
	}

}
