// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State } from '../../types';
import type { Vec3 } from 'vec3';

export class ClientboundMoveVehiclePacket extends DripleafPacket {
	static readonly id = 0x39;
	static readonly state = State.Play;
	static readonly direction = Direction.Clientbound;

	override readonly id = ClientboundMoveVehiclePacket.id;
	override readonly state = ClientboundMoveVehiclePacket.state;
	override readonly direction = ClientboundMoveVehiclePacket.direction;

	constructor(
		public position: Vec3,
		public yaw: number,
		public pitch: number,
	) {
		super();
	}

	write(writer: PacketWriter) {
		writer.writeVec3d(this.position);
		writer.writeFloat(this.yaw);
		writer.writeFloat(this.pitch);
	}

	static read(reader: PacketReader): ClientboundMoveVehiclePacket {
		const position = reader.readVec3d();
		const yaw = reader.readFloat();
		const pitch = reader.readFloat();
		return new ClientboundMoveVehiclePacket(position, yaw, pitch);
	}
}