// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundMoveMinecartAlongTrackPacket extends DripleafPacket {
	static readonly codec = packetCodec<ClientboundMoveMinecartAlongTrackPacket>({
		encode(writer: PacketWriter, value: ClientboundMoveMinecartAlongTrackPacket) {
			throw new Error("TODO: implement codec encode");
		},
		decode(reader: PacketReader): ClientboundMoveMinecartAlongTrackPacket {
			throw new Error("TODO: implement codec decode");
		},
	});

	constructor(
		public entityId: number,
		// todo: new minecart behavior???, it isn't even close to being documented and i don't have time for this
	) {
		super();
	}

}
