// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { type PacketReader, type PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import type { Vec3 } from 'vec3';

function packDegrees(angle: number): number {
	const value = Math.floor(angle * 256 / 360);
	const unsigned = value & 0xFF;
	return unsigned > 127 ? unsigned - 256 : unsigned;
}

function unpackDegrees(rot: number): number {
	return rot * 360 / 256;
}

export type MinecartStep = {
	position: Vec3;
	movement: Vec3;
	yRot: number;
	xRot: number;
	weight: number;
};

function encodeMinecartStep(writer: PacketWriter, step: MinecartStep) {
	writer.writeVec3d(step.position);
	writer.writeVec3d(step.movement);
	writer.writeByte(packDegrees(step.yRot));
	writer.writeByte(packDegrees(step.xRot));
	writer.writeFloat(step.weight);
}

function decodeMinecartStep(reader: PacketReader): MinecartStep {
	return {
		position: reader.readVec3d(),
		movement: reader.readVec3d(),
		yRot: unpackDegrees(reader.readByte()),
		xRot: unpackDegrees(reader.readByte()),
		weight: reader.readFloat(),
	};
}

export class ClientboundMoveMinecartAlongTrackPacket extends DripleafPacket {
	static readonly codec = packetCodec({
		encode(writer: PacketWriter, value: ClientboundMoveMinecartAlongTrackPacket) {
			writer.writeVarInt(value.entityId);
			writer.writeArray(value.lerpSteps, step => encodeMinecartStep(writer, step));
		},
		decode(reader: PacketReader): ClientboundMoveMinecartAlongTrackPacket {
			const entityId = reader.readVarInt();
			const lerpSteps = reader.readArray(() => decodeMinecartStep(reader));
			return new ClientboundMoveMinecartAlongTrackPacket(entityId, lerpSteps);
		},
	});

	constructor(
		public entityId: number,
		public lerpSteps: MinecartStep[],
	) {
		super();
	}
}
