// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundMoveEntityRotPacket extends DripleafPacket {
	static readonly codec = packetCodec<ClientboundMoveEntityRotPacket>({
		encode(writer: PacketWriter, value: ClientboundMoveEntityRotPacket) {
		writer.writeVarInt(value.entityId);
		writer.writeByte(value.yaw);
		writer.writeByte(value.pitch);
		writer.writeBoolean(value.onGround);
		},
		decode(reader: PacketReader): ClientboundMoveEntityRotPacket {
		const entityId = reader.readVarInt();
		const yaw = reader.readByte();
		const pitch = reader.readByte();
		const onGround = reader.readBoolean();
		return new ClientboundMoveEntityRotPacket(entityId, yaw, pitch, onGround);
		},
	});

	constructor(
		public entityId: number,
		public yaw: number,
		public pitch: number,
		public onGround: boolean
	) {
		super();
	}

}
