// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State } from '../../types';

export class ClientboundMoveEntityPosRotPacket extends DripleafPacket {
	static readonly id = 0x36;
	static readonly state = State.Play;
	static readonly direction = Direction.Clientbound;

	override readonly id = ClientboundMoveEntityPosRotPacket.id;
	override readonly state = ClientboundMoveEntityPosRotPacket.state;
	override readonly direction = ClientboundMoveEntityPosRotPacket.direction;

	constructor(
		public entityId: number,
		public deltaX: number,
		public deltaY: number,
		public deltaZ: number,
		public yaw: number,
		public pitch: number,
		public onGround: boolean
	) {
		super();
	}

	write(writer: PacketWriter) {
		writer.writeVarInt(this.entityId);
		writer.writeShort(this.deltaX);
		writer.writeShort(this.deltaY);
		writer.writeShort(this.deltaZ);
		writer.writeByte(this.yaw);
		writer.writeByte(this.pitch);
		writer.writeBoolean(this.onGround);
	}

	static read(reader: PacketReader): ClientboundMoveEntityPosRotPacket {
		const entityId = reader.readVarInt();
		const deltaX = reader.readShort();
		const deltaY = reader.readShort();
		const deltaZ = reader.readShort();
		const yaw = reader.readByte();
		const pitch = reader.readByte();
		const onGround = reader.readBoolean();
		return new ClientboundMoveEntityPosRotPacket(entityId, deltaX, deltaY, deltaZ, yaw, pitch, onGround);
	}
}