// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State } from '../../types';

export class ClientboundMoveEntityPosPacket extends DripleafPacket {
	static readonly id = 0x35;
	static readonly state = State.Play;
	static readonly direction = Direction.Clientbound;

	override readonly id = ClientboundMoveEntityPosPacket.id;
	override readonly state = ClientboundMoveEntityPosPacket.state;
	override readonly direction = ClientboundMoveEntityPosPacket.direction;

	constructor(
		public entityId: number,
		public deltaX: number,
		public deltaY: number,
		public deltaZ: number,
		public onGround: boolean
	) {
		super();
	}

	write(writer: PacketWriter) {
		writer.writeVarInt(this.entityId);
		writer.writeShort(this.deltaX);
		writer.writeShort(this.deltaY);
		writer.writeShort(this.deltaZ);
		writer.writeBoolean(this.onGround);
	}

	static read(reader: PacketReader): ClientboundMoveEntityPosPacket {
		const entityId = reader.readVarInt();
		const deltaX = reader.readShort();
		const deltaY = reader.readShort();
		const deltaZ = reader.readShort();
		const onGround = reader.readBoolean();
		return new ClientboundMoveEntityPosPacket(entityId, deltaX, deltaY, deltaZ, onGround);
	}
}