// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundMoveEntityPosRotPacket extends DripleafPacket {
	static readonly codec = packetCodec<ClientboundMoveEntityPosRotPacket>({
		encode(writer: PacketWriter, value: ClientboundMoveEntityPosRotPacket) {
		writer.writeVarInt(value.entityId);
		writer.writeShort(value.deltaX);
		writer.writeShort(value.deltaY);
		writer.writeShort(value.deltaZ);
		writer.writeByte(value.yaw);
		writer.writeByte(value.pitch);
		writer.writeBoolean(value.onGround);
		},
		decode(reader: PacketReader): ClientboundMoveEntityPosRotPacket {
		const entityId = reader.readVarInt();
		const deltaX = reader.readShort();
		const deltaY = reader.readShort();
		const deltaZ = reader.readShort();
		const yaw = reader.readByte();
		const pitch = reader.readByte();
		const onGround = reader.readBoolean();
		return new ClientboundMoveEntityPosRotPacket(entityId, deltaX, deltaY, deltaZ, yaw, pitch, onGround);
		},
	});

	constructor(
		public entityId: number,
		public deltaX: number,
		public deltaY: number,
		public deltaZ: number,
		public yaw: number,
		public pitch: number,
		public onGround: boolean
	) {
		super();
	}

}
