// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State } from '../../types';

export class ClientboundMoveEntityRotPacket extends DripleafPacket {
	static readonly id = 0x38;
	static readonly state = State.Play;
	static readonly direction = Direction.Clientbound;

	override readonly id = ClientboundMoveEntityRotPacket.id;
	override readonly state = ClientboundMoveEntityRotPacket.state;
	override readonly direction = ClientboundMoveEntityRotPacket.direction;

	constructor(
		public entityId: number,
		public yaw: number,
		public pitch: number,
		public onGround: boolean
	) {
		super();
	}

	write(writer: PacketWriter) {
		writer.writeVarInt(this.entityId);
		writer.writeByte(this.yaw);
		writer.writeByte(this.pitch);
		writer.writeBoolean(this.onGround);
	}

	static read(reader: PacketReader): ClientboundMoveEntityRotPacket {
		const entityId = reader.readVarInt();
		const yaw = reader.readByte();
		const pitch = reader.readByte();
		const onGround = reader.readBoolean();
		return new ClientboundMoveEntityRotPacket(entityId, yaw, pitch, onGround);
	}
}