// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import type { Vec3 } from 'vec3';

export class ClientboundMoveVehiclePacket extends DripleafPacket {
	static readonly codec = packetCodec<ClientboundMoveVehiclePacket>({
		encode(writer: PacketWriter, value: ClientboundMoveVehiclePacket) {
		writer.writeVec3d(value.position);
		writer.writeFloat(value.yaw);
		writer.writeFloat(value.pitch);
		},
		decode(reader: PacketReader): ClientboundMoveVehiclePacket {
		const position = reader.readVec3d();
		const yaw = reader.readFloat();
		const pitch = reader.readFloat();
		return new ClientboundMoveVehiclePacket(position, yaw, pitch);
		},
	});

	constructor(
		public position: Vec3,
		public yaw: number,
		public pitch: number,
	) {
		super();
	}

}
