// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State, type Position } from '../../types';

export class ClientboundOpenSignEditorPacket extends DripleafPacket {
	static readonly id = 0x3c;
	static readonly state = State.Play;
	static readonly direction = Direction.Clientbound;

	override readonly id = ClientboundOpenSignEditorPacket.id;
	override readonly state = ClientboundOpenSignEditorPacket.state;
	override readonly direction = ClientboundOpenSignEditorPacket.direction;

	constructor(
		public position: Position,
		public isFrontText: boolean
	) {
		super();
	}

	write(writer: PacketWriter) {
		writer.writePosition(this.position);
		writer.writeBoolean(this.isFrontText);
	}

	static read(reader: PacketReader): ClientboundOpenSignEditorPacket {
		const position = reader.readPosition();
		const isFrontText = reader.readBoolean();
		return new ClientboundOpenSignEditorPacket(position, isFrontText);
	}
}