// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import { InteractionHand } from '../../types';

export class ClientboundOpenBookPacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundOpenBookPacket, {
		hand: Codecs.byteEnum(InteractionHand),
	});

	constructor(
		public hand: InteractionHand
	) {
		super();
	}
}