// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

enum Hand {
	MainHand = 0,
	OffHand = 1
}

export class ClientboundOpenBookPacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundOpenBookPacket, {
		hand: Codecs.varInt,
	});

	constructor(
		public hand: Hand
	) {
		super();
	}

}
