// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import type { UnnamedNbtTag } from '@dripleaf/nbt';

export class ClientboundOpenScreenPacket extends DripleafPacket {
	static readonly codec = packetCodec<ClientboundOpenScreenPacket>({
		encode(writer: PacketWriter, value: ClientboundOpenScreenPacket) {
		writer.writeVarInt(value.containerId);
		writer.writeVarInt(value.type);
		writer.writeNbt(value.title);
		},
		decode(reader: PacketReader): ClientboundOpenScreenPacket {
		const containerId = reader.readVarInt();
		const type = reader.readVarInt();
		const title = reader.readNbt();
		return new ClientboundOpenScreenPacket(containerId, type, title);
		},
	});

	constructor(
		public containerId: number,
		public type: number,
		public title: UnnamedNbtTag
	) {
		super();
	}

}
