// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State } from '../../types';

export class ClientboundPlayerCombatEnterPacket extends DripleafPacket {
	static readonly id = 0x43;
	static readonly state = State.Play;
	static readonly direction = Direction.Clientbound;

	override readonly id = ClientboundPlayerCombatEnterPacket.id;
	override readonly state = ClientboundPlayerCombatEnterPacket.state;
	override readonly direction = ClientboundPlayerCombatEnterPacket.direction;

	constructor() {
		super();
	}

	write(writer: PacketWriter) {
		void writer;
	}

	static read(reader: PacketReader): ClientboundPlayerCombatEnterPacket {
		void reader;
		return new ClientboundPlayerCombatEnterPacket();
	}
}