// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundPlayerInfoRemovePacket extends DripleafPacket {
	static readonly codec = packetCodec<ClientboundPlayerInfoRemovePacket>({
		encode(writer: PacketWriter, value: ClientboundPlayerInfoRemovePacket) {
		writer.writeArray(value.profileIds, (id) => writer.writeUUID(id));
		},
		decode(reader: PacketReader): ClientboundPlayerInfoRemovePacket {
		const profileIds = reader.readArray(() => reader.readUUID());
		return new ClientboundPlayerInfoRemovePacket(profileIds);
		},
	});

	constructor(
		public profileIds: string[]
	) {
		super();
	}

}
