// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

type Abilities = {
	invulnerable: boolean;
	isFlying: boolean;
	canFly: boolean;
	instabuild: boolean;
	flyingSpeed: number;
	walkingSpeed: number;
};

export class ClientboundPlayerAbilitiesPacket extends DripleafPacket {
	static readonly codec = packetCodec<ClientboundPlayerAbilitiesPacket>({
		encode(writer: PacketWriter, value: ClientboundPlayerAbilitiesPacket) {
		writer.writeByte(
			(value.abilities.invulnerable ? 0x01 : 0) |
			(value.abilities.isFlying ? 0x02 : 0) |
			(value.abilities.canFly ? 0x04 : 0) |
			(value.abilities.instabuild ? 0x08 : 0)
		);
		writer.writeFloat(value.abilities.flyingSpeed);
		writer.writeFloat(value.abilities.walkingSpeed);
		},
		decode(reader: PacketReader): ClientboundPlayerAbilitiesPacket {
		const flags = reader.readByte();
		const abilities = {
			invulnerable: (flags & 0x01) !== 0,
			isFlying: (flags & 0x02) !== 0,
			canFly: (flags & 0x04) !== 0,
			instabuild: (flags & 0x08) !== 0,
			flyingSpeed: reader.readFloat(),
			walkingSpeed: reader.readFloat()
		};
		return new ClientboundPlayerAbilitiesPacket(abilities);
		},
	});

	constructor(
		public abilities: Abilities
	) {
		super();
	}

}
