// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State } from '../../types';
import { PositionMoveRotation } from '../../datatypes/PositionMoveRotation';

export enum Relative {
	X = 1 << 0,
	Y = 1 << 1,
	Z = 1 << 2,
	Yaw = 1 << 3,
	Pitch = 1 << 4,
	DeltaX = 1 << 5,
	DeltaY = 1 << 6,
	DeltaZ = 1 << 7,
	YawDelta = 1 << 8
}

export class ClientboundPlayerPositionPacket extends DripleafPacket {
	static readonly id = 0x48;
	static readonly state = State.Play;
	static readonly direction = Direction.Clientbound;

	override readonly id = ClientboundPlayerPositionPacket.id;
	override readonly state = ClientboundPlayerPositionPacket.state;
	override readonly direction = ClientboundPlayerPositionPacket.direction;

	constructor(
		public teleportId: number,
		public change: PositionMoveRotation,
		public relatives: Relative
	) {
		super();
	}

	write(writer: PacketWriter) {
		writer.writeVarInt(this.teleportId);
		this.change.write(writer);
		writer.writeByte(this.relatives);
	}

	static read(reader: PacketReader): ClientboundPlayerPositionPacket {
		const teleportId = reader.readVarInt();
		const change = PositionMoveRotation.read(reader);
		const relatives = reader.readByte();
		return new ClientboundPlayerPositionPacket(teleportId, change, relatives);
	}
}