// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import { PositionMoveRotation } from '../../datatypes/PositionMoveRotation';

export enum Relative {
	X = 1 << 0,
	Y = 1 << 1,
	Z = 1 << 2,
	Yaw = 1 << 3,
	Pitch = 1 << 4,
	DeltaX = 1 << 5,
	DeltaY = 1 << 6,
	DeltaZ = 1 << 7,
	YawDelta = 1 << 8
}

export class ClientboundPlayerPositionPacket extends DripleafPacket {
	static readonly codec = packetCodec<ClientboundPlayerPositionPacket>({
		encode(writer: PacketWriter, value: ClientboundPlayerPositionPacket) {
		writer.writeVarInt(value.teleportId);
		writer.writeCodec(PositionMoveRotation.codec, value.change);
		writer.writeByte(value.relatives);
		},
		decode(reader: PacketReader): ClientboundPlayerPositionPacket {
		const teleportId = reader.readVarInt();
		const change = reader.readCodec(PositionMoveRotation.codec);
		const relatives = reader.readByte();
		return new ClientboundPlayerPositionPacket(teleportId, change, relatives);
		},
	});

	constructor(
		public teleportId: number,
		public change: PositionMoveRotation,
		public relatives: Relative
	) {
		super();
	}

}
