// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PositionMoveRotation } from '@dripleaf/core';
import { PositionMoveRotationCodec } from '../../datatypes/PositionMoveRotation';
import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export enum Relative {
	X = 1 << 0,
	Y = 1 << 1,
	Z = 1 << 2,
	Yaw = 1 << 3,
	Pitch = 1 << 4,
	DeltaX = 1 << 5,
	DeltaY = 1 << 6,
	DeltaZ = 1 << 7,
	YawDelta = 1 << 8
}

export class ClientboundPlayerPositionPacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundPlayerPositionPacket, {
		teleportId: Codecs.varInt,
		change: PositionMoveRotationCodec,
		relatives: Codecs.int,
	});

	constructor(
		public teleportId: number,
		public change: PositionMoveRotation,
		public relatives: Relative
	) {
		super();
	}
}