// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundPlayerCombatEndPacket extends DripleafPacket {
	static readonly codec = packetCodec<ClientboundPlayerCombatEndPacket>({
		encode(writer: PacketWriter, value: ClientboundPlayerCombatEndPacket) {
		writer.writeVarInt(value.duration);
		},
		decode(reader: PacketReader): ClientboundPlayerCombatEndPacket {
		const duration = reader.readVarInt();
		return new ClientboundPlayerCombatEndPacket(duration);
		},
	});

	constructor(
		public duration: number,
	) {
		super();
	}

}
