// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State } from '../../types';

export class ClientboundPlayerRotationPacket extends DripleafPacket {
	static readonly id = 0x49;
	static readonly state = State.Play;
	static readonly direction = Direction.Clientbound;

	override readonly id = ClientboundPlayerRotationPacket.id;
	override readonly state = ClientboundPlayerRotationPacket.state;
	override readonly direction = ClientboundPlayerRotationPacket.direction;

	constructor(
		public yaw: number,
		public relativeYaw: boolean,
		public pitch: number,
		public relativePitch: boolean
	) {
		super();
	}

	write(writer: PacketWriter) {
		writer.writeFloat(this.yaw);
		writer.writeBoolean(this.relativeYaw);
		writer.writeFloat(this.pitch);
		writer.writeBoolean(this.relativePitch);
	}

	static read(reader: PacketReader): ClientboundPlayerRotationPacket {
		const yaw = reader.readFloat();
		const relativeYaw = reader.readBoolean();
		const pitch = reader.readFloat();
		const relativePitch = reader.readBoolean();
		return new ClientboundPlayerRotationPacket(yaw, relativeYaw, pitch, relativePitch);
	}
}