// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State } from '../../types';
import type { UnnamedNbtTag } from '@dripleaf/nbt';

export class ClientboundPlayerCombatKillPacket extends DripleafPacket {
	static readonly id = 0x44;
	static readonly state = State.Play;
	static readonly direction = Direction.Clientbound;

	override readonly id = ClientboundPlayerCombatKillPacket.id;
	override readonly state = ClientboundPlayerCombatKillPacket.state;
	override readonly direction = ClientboundPlayerCombatKillPacket.direction;

	constructor(
		public playerId: number,
		public message: UnnamedNbtTag
	) {
		super();
	}

	write(writer: PacketWriter) {
		writer.writeVarInt(this.playerId);
		writer.writeNbt(this.message);
	}

	static read(reader: PacketReader): ClientboundPlayerCombatKillPacket {
		const playerId = reader.readVarInt();
		const message = reader.readNbt();
		return new ClientboundPlayerCombatKillPacket(playerId, message);
	}
}