// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import type { UnnamedNbtTag } from '@dripleaf/nbt';

export class ClientboundPlayerCombatKillPacket extends DripleafPacket {
	static readonly codec = packetCodec<ClientboundPlayerCombatKillPacket>({
		encode(writer: PacketWriter, value: ClientboundPlayerCombatKillPacket) {
		writer.writeVarInt(value.playerId);
		writer.writeNbt(value.message);
		},
		decode(reader: PacketReader): ClientboundPlayerCombatKillPacket {
		const playerId = reader.readVarInt();
		const message = reader.readNbt();
		return new ClientboundPlayerCombatKillPacket(playerId, message);
		},
	});

	constructor(
		public playerId: number,
		public message: UnnamedNbtTag
	) {
		super();
	}

}
