// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs, type PacketReader, type PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundPlaceGhostRecipePacket extends DripleafPacket {
	static readonly codec = packetCodec({
		encode(writer: PacketWriter, value: ClientboundPlaceGhostRecipePacket) {
			writer.writeVarInt(value.containerId);
			writer.writeBytes(value.recipeDisplay);
		},
		decode(reader: PacketReader): ClientboundPlaceGhostRecipePacket {
			const containerId = reader.readVarInt();
			const recipeDisplay = reader.readRemaining();
			return new ClientboundPlaceGhostRecipePacket(containerId, recipeDisplay);
		},
	});

	constructor(
		public containerId: number,
		public recipeDisplay: Uint8Array,
	) {
		super();
	}

}
