// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State } from '../../types';

export class ClientboundPlayerCombatEndPacket extends DripleafPacket {
	static readonly id = 0x42;
	static readonly state = State.Play;
	static readonly direction = Direction.Clientbound;

	override readonly id = ClientboundPlayerCombatEndPacket.id;
	override readonly state = ClientboundPlayerCombatEndPacket.state;
	override readonly direction = ClientboundPlayerCombatEndPacket.direction;

	constructor(
		public duration: number,
	) {
		super();
	}

	write(writer: PacketWriter) {
		writer.writeVarInt(this.duration);
	}

	static read(reader: PacketReader): ClientboundPlayerCombatEndPacket {
		const duration = reader.readVarInt();
		return new ClientboundPlayerCombatEndPacket(duration);
	}
}