// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import type { UnnamedNbtTag } from '@dripleaf/nbt';
import type { UUID } from 'node:crypto';

export enum PlayerInfoUpdateAction {
	AddPlayer = 0x01,
	InitializeChat = 0x02,
	UpdateGameMode = 0x04,
	UpdateListed = 0x08,
	UpdateLatency = 0x10,
	UpdateDisplayName = 0x20,
	UpdateHat = 0x40,
	UpdateListOrder = 0x80
}

export type GameProfileProperty = {
	name: string;
	value: string;
	signature: string | null;
}

export type PlayerInfoProfile = {
	name: string;
	properties: GameProfileProperty[];
}

export type PlayerInfoPublicKey = {
	expireTime: bigint;
	keyBytes: Uint8Array;
	keySignature: Uint8Array;
}

export type PlayerInfoChatSession = {
	uuid: UUID;
	publicKey: PlayerInfoPublicKey;
}

export type PlayerInfoEntry = {
	uuid: UUID;
	player?: PlayerInfoProfile;
	chatSession?: PlayerInfoChatSession | null;
	gameMode?: number;
	listed?: boolean;
	latency?: number;
	displayName?: UnnamedNbtTag | null;
	listOrder?: number;
	showHat?: boolean;
}

export class ClientboundPlayerInfoUpdatePacket extends DripleafPacket {
	static readonly codec = packetCodec<ClientboundPlayerInfoUpdatePacket>({
		encode(writer: PacketWriter, value: ClientboundPlayerInfoUpdatePacket) {
		writer.writeUnsignedByte(value.actions);
		writer.writeVarInt(value.entries.length);

		for (const entry of value.entries) {
			writer.writeUUID(entry.uuid);

			if (value.actions & PlayerInfoUpdateAction.AddPlayer) {
				if (entry.player == null)
					throw new Error("Player info update doesn't have add-player profile data");

				writer.writeString(entry.player.name, 16);
				writer.writeArray(entry.player.properties, (property) => {
					writer.writeString(property.name, 64);
					writer.writeString(property.value);
					writer.writePrefixedOptional(property.signature, signature => writer.writeString(signature, 1024));
				});
			}

			if (value.actions & PlayerInfoUpdateAction.InitializeChat) {
				writer.writePrefixedOptional(entry.chatSession, session => {
					writer.writeUUID(session.uuid);
					writer.writeLong(session.publicKey.expireTime);
					writer.writeByteArray(session.publicKey.keyBytes, 512);
					writer.writeByteArray(session.publicKey.keySignature, 4096);
				});
			}

			if (value.actions & PlayerInfoUpdateAction.UpdateGameMode) {
				if (entry.gameMode == null)
					throw new Error("Player info update is missing game mode data");
				writer.writeVarInt(entry.gameMode);
			}

			if (value.actions & PlayerInfoUpdateAction.UpdateListed) {
				if (entry.listed == null)
					throw new Error("Player info update is missing listed flag data");
				writer.writeBoolean(entry.listed);
			}

			if (value.actions & PlayerInfoUpdateAction.UpdateLatency) {
				if (entry.latency == null)
					throw new Error("Player info update is missing latency data");
				writer.writeVarInt(entry.latency);
			}

			if (value.actions & PlayerInfoUpdateAction.UpdateDisplayName)
				writer.writePrefixedOptional(entry.displayName, displayName => writer.writeNbt(displayName));

			if (value.actions & PlayerInfoUpdateAction.UpdateHat) {
				if (entry.showHat == null)
					throw new Error("Player info update is missing hat visibility data");
				writer.writeBoolean(entry.showHat);
			}

			if (value.actions & PlayerInfoUpdateAction.UpdateListOrder) {
				if (entry.listOrder == null)
					throw new Error("Player info update is missing list order data");
				writer.writeVarInt(entry.listOrder);
			}
		}
		},
		decode(reader: PacketReader): ClientboundPlayerInfoUpdatePacket {
		const actions = reader.readUnsignedByte();
		const entries = reader.readArray(() => {
			const entry: PlayerInfoEntry = {
				uuid: reader.readUUID()
			};

			if (actions & PlayerInfoUpdateAction.AddPlayer) {
				const name = reader.readString();
				const propertyCount = reader.readVarInt();
				const properties: GameProfileProperty[] = [];
				for (let propertyIndex = 0; propertyIndex < propertyCount; propertyIndex++) {
					const propertyName = reader.readString();
					const propertyValue = reader.readString();
					const signature = reader.readPrefixedOptional(() => reader.readString());
					properties.push({ name: propertyName, value: propertyValue, signature });
				}
				entry.player = { name, properties };
			}

			if (actions & PlayerInfoUpdateAction.InitializeChat) {
				entry.chatSession = reader.readPrefixedOptional(() => ({
					uuid: reader.readUUID(),
					publicKey: {
						expireTime: reader.readLong(),
						keyBytes: reader.readByteArray(),
						keySignature: reader.readByteArray()
					}
				}));
			}

			if (actions & PlayerInfoUpdateAction.UpdateGameMode)
				entry.gameMode = reader.readVarInt();

			if (actions & PlayerInfoUpdateAction.UpdateListed)
				entry.listed = reader.readBoolean();

			if (actions & PlayerInfoUpdateAction.UpdateLatency)
				entry.latency = reader.readVarInt();

			if (actions & PlayerInfoUpdateAction.UpdateDisplayName)
				entry.displayName = reader.readPrefixedOptional(() => reader.readNbt());

			if (actions & PlayerInfoUpdateAction.UpdateHat)
				entry.showHat = reader.readBoolean();

			if (actions & PlayerInfoUpdateAction.UpdateListOrder)
				entry.listOrder = reader.readVarInt();

			return entry;
		});

		return new ClientboundPlayerInfoUpdatePacket(actions, entries);
		},
	});

	constructor(
		public actions: number,
		public entries: PlayerInfoEntry[]
	) {
		super();
	}

}
