// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundProjectilePowerPacket extends DripleafPacket {
	static readonly codec = packetCodec<ClientboundProjectilePowerPacket>({
		encode(writer: PacketWriter, value: ClientboundProjectilePowerPacket) {
		writer.writeVarInt(value.unknownId);
		writer.writeDouble(value.accelerationPower);
		},
		decode(reader: PacketReader): ClientboundProjectilePowerPacket {
		const unknownId = reader.readVarInt();
		const accelerationPower = reader.readDouble();
		return new ClientboundProjectilePowerPacket(unknownId, accelerationPower);
		},
	});

	constructor(
		public unknownId: number, // todo: figure out what this is (src says "id")
		public accelerationPower: number,
	) {
		super();
	}

}
