// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State } from '../../types';

export class ClientboundProjectilePowerPacket extends DripleafPacket {
	static readonly id = 0x87;
	static readonly state = State.Play;
	static readonly direction = Direction.Clientbound;

	override readonly id = ClientboundProjectilePowerPacket.id;
	override readonly state = ClientboundProjectilePowerPacket.state;
	override readonly direction = ClientboundProjectilePowerPacket.direction;

	constructor(
		public unknownId: number, // todo: figure out what this is (src says "id")
		public accelerationPower: number,
	) {
		super();
	}

	write(writer: PacketWriter) {
		writer.writeVarInt(this.unknownId);
		writer.writeDouble(this.accelerationPower);
	}

	static read(reader: PacketReader): ClientboundProjectilePowerPacket {
		const unknownId = reader.readVarInt();
		const accelerationPower = reader.readDouble();
		return new ClientboundProjectilePowerPacket(unknownId, accelerationPower);
	}
}