// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State } from '../../types';

type RecipeBookSetting = {
	open: boolean;
	filtering: boolean;
}

type RecipeBookSettings = {
	crafting: RecipeBookSetting;
	furnace: RecipeBookSetting;
	blastFurnace: RecipeBookSetting;
	smoker: RecipeBookSetting;
}

export class ClientboundRecipeBookSettingsPacket extends DripleafPacket {
	static readonly id = 0x4c;
	static readonly state = State.Play;
	static readonly direction = Direction.Clientbound;

	override readonly id = ClientboundRecipeBookSettingsPacket.id;
	override readonly state = ClientboundRecipeBookSettingsPacket.state;
	override readonly direction = ClientboundRecipeBookSettingsPacket.direction;

	constructor(
		public settings: RecipeBookSettings
	) {
		super();
	}

	write(writer: PacketWriter) {
		writer.writeBoolean(this.settings.crafting.open);
		writer.writeBoolean(this.settings.crafting.filtering);
		writer.writeBoolean(this.settings.furnace.open);
		writer.writeBoolean(this.settings.furnace.filtering);
		writer.writeBoolean(this.settings.blastFurnace.open);
		writer.writeBoolean(this.settings.blastFurnace.filtering);
		writer.writeBoolean(this.settings.smoker.open);
		writer.writeBoolean(this.settings.smoker.filtering);
	}

	static read(reader: PacketReader): ClientboundRecipeBookSettingsPacket {
		const settings: RecipeBookSettings = {
			crafting: { open: reader.readBoolean(), filtering: reader.readBoolean() },
			furnace: { open: reader.readBoolean(), filtering: reader.readBoolean() },
			blastFurnace: { open: reader.readBoolean(), filtering: reader.readBoolean() },
			smoker: { open: reader.readBoolean(), filtering: reader.readBoolean() },
		};

		return new ClientboundRecipeBookSettingsPacket(settings);
	}
}