// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundResetScorePacket extends DripleafPacket {
	static readonly codec = packetCodec<ClientboundResetScorePacket>({
		encode(writer: PacketWriter, value: ClientboundResetScorePacket) {
		writer.writeString(value.owner);
		writer.writePrefixedOptional(value.objectiveName, (objectiveName) => writer.writeString(objectiveName));
		},
		decode(reader: PacketReader): ClientboundResetScorePacket {
		const owner = reader.readString();
		const objectiveName = reader.readPrefixedOptional(() => reader.readString());
		return new ClientboundResetScorePacket(owner, objectiveName);
		},
	});

	constructor(
		public owner: string,
		public objectiveName: string | null
	) {
		super();
	}

}
