// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

type RecipeBookSetting = {
	open: boolean;
	filtering: boolean;
}

type RecipeBookSettings = {
	crafting: RecipeBookSetting;
	furnace: RecipeBookSetting;
	blastFurnace: RecipeBookSetting;
	smoker: RecipeBookSetting;
}

export class ClientboundRecipeBookSettingsPacket extends DripleafPacket {
	static readonly codec = packetCodec<ClientboundRecipeBookSettingsPacket>({
		encode(writer: PacketWriter, value: ClientboundRecipeBookSettingsPacket) {
		writer.writeBoolean(value.settings.crafting.open);
		writer.writeBoolean(value.settings.crafting.filtering);
		writer.writeBoolean(value.settings.furnace.open);
		writer.writeBoolean(value.settings.furnace.filtering);
		writer.writeBoolean(value.settings.blastFurnace.open);
		writer.writeBoolean(value.settings.blastFurnace.filtering);
		writer.writeBoolean(value.settings.smoker.open);
		writer.writeBoolean(value.settings.smoker.filtering);
		},
		decode(reader: PacketReader): ClientboundRecipeBookSettingsPacket {
		const settings: RecipeBookSettings = {
			crafting: { open: reader.readBoolean(), filtering: reader.readBoolean() },
			furnace: { open: reader.readBoolean(), filtering: reader.readBoolean() },
			blastFurnace: { open: reader.readBoolean(), filtering: reader.readBoolean() },
			smoker: { open: reader.readBoolean(), filtering: reader.readBoolean() },
		};

		return new ClientboundRecipeBookSettingsPacket(settings);
		},
	});

	constructor(
		public settings: RecipeBookSettings
	) {
		super();
	}

}
