// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundRemoveMobEffectPacket extends DripleafPacket {
	static readonly codec = packetCodec<ClientboundRemoveMobEffectPacket>({
		encode(writer: PacketWriter, value: ClientboundRemoveMobEffectPacket) {
		writer.writeVarInt(value.entityId);
		writer.writeVarInt(value.effectId);
		},
		decode(reader: PacketReader): ClientboundRemoveMobEffectPacket {
		const entityId = reader.readVarInt();
		const effectId = reader.readVarInt();
		return new ClientboundRemoveMobEffectPacket(entityId, effectId);
		},
	});

	constructor(
		public entityId: number,
		public effectId: number
	) {
		super();
	}

}
