// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State } from '../../types';

export class ClientboundRemoveMobEffectPacket extends DripleafPacket {
	static readonly id = 0x4e;
	static readonly state = State.Play;
	static readonly direction = Direction.Clientbound;

	override readonly id = ClientboundRemoveMobEffectPacket.id;
	override readonly state = ClientboundRemoveMobEffectPacket.state;
	override readonly direction = ClientboundRemoveMobEffectPacket.direction;

	constructor(
		public entityId: number,
		public effectId: number
	) {
		super();
	}

	write(writer: PacketWriter) {
		writer.writeVarInt(this.entityId);
		writer.writeVarInt(this.effectId);
	}

	static read(reader: PacketReader): ClientboundRemoveMobEffectPacket {
		const entityId = reader.readVarInt();
		const effectId = reader.readVarInt();
		return new ClientboundRemoveMobEffectPacket(entityId, effectId);
	}
}