// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { CommonPlayerSpawnInfo } from '@dripleaf/core';
import { CommonPlayerSpawnInfoCodec } from '../../datatypes/CommonPlayerSpawnInfo';
import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

enum DataToKeep {
	KeepAttributeModifiers = 1,
	KeepEntityData = 2,
	KeepAllData = 3,
}

export class ClientboundRespawnPacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundRespawnPacket, {
		commonPlayerSpawnInfo: CommonPlayerSpawnInfoCodec,
		dataToKeep: Codecs.byte,
	});

	constructor(
		public commonPlayerSpawnInfo: CommonPlayerSpawnInfo,
		public dataToKeep: DataToKeep
	) {
		super();
	}
}