// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundResetScorePacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundResetScorePacket, {
		owner: Codecs.string(),
		objectiveName: Codecs.prefixedOptional(Codecs.string())
	});

	constructor(
		public owner: string,
		public objectiveName: string | null
	) {
		super();
	}
}