// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { MobEffect } from '@dripleaf/registry';
import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundRemoveMobEffectPacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundRemoveMobEffectPacket, {
		entityId: Codecs.varInt,
		effect: Codecs.varIntEnum(MobEffect),
	});

	constructor(
		public entityId: number,
		public effect: MobEffect
	) {
		super();
	}
}