// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State } from '../../types';

export class ClientboundRemoveEntitiesPacket extends DripleafPacket {
	static readonly id = 0x4d;
	static readonly state = State.Play;
	static readonly direction = Direction.Clientbound;

	override readonly id = ClientboundRemoveEntitiesPacket.id;
	override readonly state = ClientboundRemoveEntitiesPacket.state;
	override readonly direction = ClientboundRemoveEntitiesPacket.direction;

	constructor(
		public entityIds: number[]
	) {
		super();
	}

	write(writer: PacketWriter) {
		writer.writeArray(this.entityIds, (entityId) => writer.writeVarInt(entityId));
	}

	static read(reader: PacketReader): ClientboundRemoveEntitiesPacket {
		const entityIds = reader.readArray(() => reader.readVarInt());
		return new ClientboundRemoveEntitiesPacket(entityIds);
	}
}