// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundSelectAdvancementsTabPacket extends DripleafPacket {
	static readonly codec = packetCodec<ClientboundSelectAdvancementsTabPacket>({
		encode(writer: PacketWriter, value: ClientboundSelectAdvancementsTabPacket) {
		writer.writePrefixedOptional(value.tab, writer.writeString);
		},
		decode(reader: PacketReader): ClientboundSelectAdvancementsTabPacket {
		const tab = reader.readPrefixedOptional(reader.readString);
		return new ClientboundSelectAdvancementsTabPacket(tab);
		},
	});

	constructor(
		public tab: string | null
	) {
		super();
	}

}
