// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State } from '../../types';

export class ClientboundSetScorePacket extends DripleafPacket {
	static readonly id = 0x6e;
	static readonly state = State.Play;
	static readonly direction = Direction.Clientbound;

	override readonly id = ClientboundSetScorePacket.id;
	override readonly state = ClientboundSetScorePacket.state;
	override readonly direction = ClientboundSetScorePacket.direction;

	constructor(
		// todo
	) {
		super();
	}

	write(writer: PacketWriter) {
		// todo
	}

	static read(reader: PacketReader): ClientboundSetScorePacket {
		// todo
	}
}