// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { ChatComponentCodec } from '../../datatypes';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import type { ChatComponent } from '@dripleaf/chat';

export class ClientboundServerDataPacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundServerDataPacket, {
		motd: ChatComponentCodec,
		iconBytes: Codecs.prefixedOptional(Codecs.byteArray())
	});

	constructor(
		public motd: ChatComponent,
		public iconBytes: Uint8Array | null	
	) {
		super();
	}
}