// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State, type Position } from '../../types';

export class ClientboundSetEntityMotionPacket extends DripleafPacket {
	static readonly id = 0x65;
	static readonly state = State.Play;
	static readonly direction = Direction.Clientbound;

	override readonly id = ClientboundSetEntityMotionPacket.id;
	override readonly state = ClientboundSetEntityMotionPacket.state;
	override readonly direction = ClientboundSetEntityMotionPacket.direction;

	constructor(
		public entityId: number,
		public movement: Position // todo: should be a vec3
	) {
		super();
	}

	write(writer: PacketWriter) {
		writer.writeVarInt(this.entityId);
		writer.writePosition(this.movement);
	}

	static read(reader: PacketReader): ClientboundSetEntityMotionPacket {
		const entityId = reader.readVarInt();
		const movement = reader.readPosition();
		return new ClientboundSetEntityMotionPacket(entityId, movement);
	}
}