// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { ChatComponentCodec } from '../../datatypes';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import type { ChatComponent } from '@dripleaf/chat';

export class ClientboundSetTitleTextPacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundSetTitleTextPacket, {
		text: ChatComponentCodec,
	});

	constructor(
		public text: ChatComponent,
	) {
		super();
	}
}