// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundSetBorderCenterPacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundSetBorderCenterPacket, {
		newCenterX: Codecs.double,
		newCenterZ: Codecs.double,
	});

	constructor(
		public newCenterX: number,
		public newCenterZ: number
	) {
		super();
	}

}
