// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State } from '../../types';

export class ClientboundSetBorderSizePacket extends DripleafPacket {
	static readonly id = 0x5a;
	static readonly state = State.Play;
	static readonly direction = Direction.Clientbound;

	override readonly id = ClientboundSetBorderSizePacket.id;
	override readonly state = ClientboundSetBorderSizePacket.state;
	override readonly direction = ClientboundSetBorderSizePacket.direction;

	constructor(
		public size: number
	) {
		super();
	}

	write(writer: PacketWriter) {
		writer.writeDouble(this.size);
	}

	static read(reader: PacketReader): ClientboundSetBorderSizePacket {
		const size = reader.readDouble();
		return new ClientboundSetBorderSizePacket(size);
	}
}