// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import { RespawnData } from '../../datatypes/RespawnData';

export class ClientboundSetDefaultSpawnPositionPacket extends DripleafPacket {
	static readonly codec = packetCodec<ClientboundSetDefaultSpawnPositionPacket>({
		encode(writer: PacketWriter, value: ClientboundSetDefaultSpawnPositionPacket) {
		writer.writeCodec(RespawnData.codec, value.respawnData);
		},
		decode(reader: PacketReader): ClientboundSetDefaultSpawnPositionPacket {
		const respawnData = reader.readCodec(RespawnData.codec);
		return new ClientboundSetDefaultSpawnPositionPacket(respawnData);
		},
	});

	constructor(
		public respawnData: RespawnData
	) {
		super();
	}

}
