// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State } from '../../types';

export class ClientboundSetBorderWarningDelayPacket extends DripleafPacket {
	static readonly id = 0x5b;
	static readonly state = State.Play;
	static readonly direction = Direction.Clientbound;

	override readonly id = ClientboundSetBorderWarningDelayPacket.id;
	override readonly state = ClientboundSetBorderWarningDelayPacket.state;
	override readonly direction = ClientboundSetBorderWarningDelayPacket.direction;

	constructor(
		public delay: number
	) {
		super();
	}

	write(writer: PacketWriter) {
		writer.writeVarInt(this.delay);
	}

	static read(reader: PacketReader): ClientboundSetBorderWarningDelayPacket {
		const delay = reader.readVarInt();
		return new ClientboundSetBorderWarningDelayPacket(delay);
	}
}