// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundSetTitlesAnimationPacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundSetTitlesAnimationPacket, {
		fadeIn: Codecs.int,
		stay: Codecs.int,
		fadeOut: Codecs.int,	
	});

	constructor(
		public fadeIn: number,
		public stay: number,
		public fadeOut: number,
	) {
		super();
	}
}