// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundSetBorderWarningDistancePacket extends DripleafPacket {
	static readonly codec = packetCodec<ClientboundSetBorderWarningDistancePacket>({
		encode(writer: PacketWriter, value: ClientboundSetBorderWarningDistancePacket) {
		writer.writeVarInt(value.warningBlocks);
		},
		decode(reader: PacketReader): ClientboundSetBorderWarningDistancePacket {
		const warningBlocks = reader.readVarInt();
		return new ClientboundSetBorderWarningDistancePacket(warningBlocks);
		},
	});

	constructor(
		public warningBlocks: number
	) {
		super();
	}

}
