// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { RespawnData } from '@dripleaf/core';
import { RespawnDataCodec } from '../../datatypes/RespawnData';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundSetDefaultSpawnPositionPacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundSetDefaultSpawnPositionPacket, {
		respawnData: RespawnDataCodec
	});

	constructor(
		public respawnData: RespawnData
	) {
		super();
	}
}