// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State, type Position } from '../../types';

type GlobalPosition = {
	dimension: string;
	position: Position;
}

type RespawnData = {
	globalPosition: GlobalPosition;
	yaw: number;
	pitch: number;
}

export class ClientboundSetDefaultSpawnPositionPacket extends DripleafPacket {
	static readonly id = 0x61;
	static readonly state = State.Play;
	static readonly direction = Direction.Clientbound;

	override readonly id = ClientboundSetDefaultSpawnPositionPacket.id;
	override readonly state = ClientboundSetDefaultSpawnPositionPacket.state;
	override readonly direction = ClientboundSetDefaultSpawnPositionPacket.direction;

	constructor(
		public respawnData: RespawnData
	) {
		super();
	}

	write(writer: PacketWriter) {
		writer.writeString(this.respawnData.globalPosition.dimension);
		writer.writePosition(this.respawnData.globalPosition.position);
		writer.writeFloat(this.respawnData.yaw);
		writer.writeFloat(this.respawnData.pitch);
	}

	static read(reader: PacketReader): ClientboundSetDefaultSpawnPositionPacket {
		const dimension = reader.readString();
		const position = reader.readPosition();
		const yaw = reader.readFloat();
		const pitch = reader.readFloat();
		return new ClientboundSetDefaultSpawnPositionPacket({
			globalPosition: {
				dimension,
				position
			},
			yaw,
			pitch
		});
	}
}