// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs, type PacketReader, type PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export type ClockNetworkState = {
	totalTicks: bigint;
	partialTick: number;
	rate: number;
};

export class ClientboundSetTimePacket extends DripleafPacket {
	static readonly codec = packetCodec({
		encode(writer: PacketWriter, value: ClientboundSetTimePacket) {
			Codecs.long.encode(writer, value.gameTime);
			writer.writeVarInt(value.clockUpdates.size);
			for (const [worldClock, state] of value.clockUpdates) {
				writer.writeVarInt(worldClock);
				writer.writeVarLong(state.totalTicks);
				writer.writeFloat(state.partialTick);
				writer.writeFloat(state.rate);
			}
		},
		decode(reader: PacketReader): ClientboundSetTimePacket {
			const gameTime = Codecs.long.decode(reader);
			const clockUpdates = new Map<number, ClockNetworkState>();
			const clockCount = reader.readVarInt();
			for (let i = 0; i < clockCount; i++) {
				const worldClock = reader.readVarInt();
				const state: ClockNetworkState = {
					totalTicks: reader.readVarLong(),
					partialTick: reader.readFloat(),
					rate: reader.readFloat(),
				};
				clockUpdates.set(worldClock, state);
			}
			return new ClientboundSetTimePacket(gameTime, clockUpdates);
		},
	});

	constructor(
		public gameTime: bigint,
		public clockUpdates: Map<number, ClockNetworkState>,
	) {
		super();
	}

}
