// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State } from '../../types';

export class ClientboundSetBorderWarningDistancePacket extends DripleafPacket {
	static readonly id = 0x5c;
	static readonly state = State.Play;
	static readonly direction = Direction.Clientbound;

	override readonly id = ClientboundSetBorderWarningDistancePacket.id;
	override readonly state = ClientboundSetBorderWarningDistancePacket.state;
	override readonly direction = ClientboundSetBorderWarningDistancePacket.direction;

	constructor(
		public warningBlocks: number
	) {
		super();
	}

	write(writer: PacketWriter) {
		writer.writeVarInt(this.warningBlocks);
	}

	static read(reader: PacketReader): ClientboundSetBorderWarningDistancePacket {
		const warningBlocks = reader.readVarInt();
		return new ClientboundSetBorderWarningDistancePacket(warningBlocks);
	}
}