// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { codec, Codecs } from '../../buffer';
import { ChatComponentCodec } from '../../datatypes';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import type { ServerLink, ServerLinkType } from '../common';
import type { ChatComponent } from '@dripleaf/chat';

export class ClientboundServerLinksPacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundServerLinksPacket, {
		links: Codecs.array(codec({
			encode(writer, value) {
				writer.writeEither<ServerLinkType, ChatComponent>(
					value.label,
					label => writer.writeVarInt(label),
					label => ChatComponentCodec.encode(writer, label),
				)
				writer.writeString(value.url)
			},
			decode(reader) {
				const label = reader.readEither<ServerLinkType, ChatComponent>(
					() => reader.readVarInt(),
					() => ChatComponentCodec.decode(reader),
				)
				const url = reader.readString()
				return { label, url }
			},
		})),
	});

	constructor(
		public links: ServerLink[]
	) {
		super();
	}
}