// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { ItemStackCodec } from '../common';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundSetPlayerInventoryPacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundSetPlayerInventoryPacket, {
		slot: Codecs.varInt,
		contents: ItemStackCodec,
	});

	constructor(
		public slot: number,
		public contents: object,
	) {
		super();
	}

}
