// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { type PacketReader, type PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundSetEntityDataPacket extends DripleafPacket {
	static readonly codec = packetCodec({
		encode(writer: PacketWriter, value: ClientboundSetEntityDataPacket) {
			writer.writeVarInt(value.entityId);
			writer.writeBytes(value.packedItems);
		},
		decode(reader: PacketReader): ClientboundSetEntityDataPacket {
			const entityId = reader.readVarInt();
			const packedItems = reader.readRemaining();
			return new ClientboundSetEntityDataPacket(entityId, packedItems);
		},
	});

	constructor(
		public entityId: number,
		public packedItems: Uint8Array,
	) {
		super();
	}
}
