// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State } from '../../types';

export class ClientboundSetExperiencePacket extends DripleafPacket {
	static readonly id = 0x67;
	static readonly state = State.Play;
	static readonly direction = Direction.Clientbound;

	override readonly id = ClientboundSetExperiencePacket.id;
	override readonly state = ClientboundSetExperiencePacket.state;
	override readonly direction = ClientboundSetExperiencePacket.direction;

	constructor(
		public experienceProgress: number,
		public totalExperience: number,
		public experienceLevel: number
	) {
		super();
	}

	write(writer: PacketWriter) {
		writer.writeFloat(this.experienceProgress);
		writer.writeVarInt(this.totalExperience);
		writer.writeVarInt(this.experienceLevel);
	}

	static read(reader: PacketReader): ClientboundSetExperiencePacket {
		const experienceProgress = reader.readFloat();
		const totalExperience = reader.readVarInt();
		const experienceLevel = reader.readVarInt();
		return new ClientboundSetExperiencePacket(experienceProgress, totalExperience, experienceLevel);
	}
}