// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import type { UnnamedNbtTag } from '@dripleaf/nbt';

export class ClientboundServerDataPacket extends DripleafPacket {
	static readonly codec = packetCodec<ClientboundServerDataPacket>({
		encode(writer: PacketWriter, value: ClientboundServerDataPacket) {
		writer.writeNbt(value.motd);
		writer.writePrefixedOptional(value.iconBytes, writer.writeByteArray);
		},
		decode(reader: PacketReader): ClientboundServerDataPacket {
		const motd = reader.readNbt();
		const iconBytes = reader.readPrefixedOptional(reader.readByteArray);
		return new ClientboundServerDataPacket(motd, iconBytes);
		},
	});

	constructor(
		public motd: UnnamedNbtTag,
		public iconBytes: Uint8Array | null	
	) {
		super();
	}

}
