// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State } from '../../types';

export class ClientboundSelectAdvancementsTabPacket extends DripleafPacket {
	static readonly id = 0x55;
	static readonly state = State.Play;
	static readonly direction = Direction.Clientbound;

	override readonly id = ClientboundSelectAdvancementsTabPacket.id;
	override readonly state = ClientboundSelectAdvancementsTabPacket.state;
	override readonly direction = ClientboundSelectAdvancementsTabPacket.direction;

	constructor(
		public tab: string | null
	) {
		super();
	}

	write(writer: PacketWriter) {
		writer.writePrefixedOptional(this.tab, writer.writeString);
	}

	static read(reader: PacketReader): ClientboundSelectAdvancementsTabPacket {
		const tab = reader.readPrefixedOptional(reader.readString);
		return new ClientboundSelectAdvancementsTabPacket(tab);
	}
}