// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import type { UnnamedNbtTag } from '@dripleaf/nbt';

export class ClientboundSetActionBarTextPacket extends DripleafPacket {
	static readonly codec = packetCodec<ClientboundSetActionBarTextPacket>({
		encode(writer: PacketWriter, value: ClientboundSetActionBarTextPacket) {
		writer.writeNbt(value.text);
		},
		decode(reader: PacketReader): ClientboundSetActionBarTextPacket {
		const text = reader.readNbt();
		return new ClientboundSetActionBarTextPacket(text);
		},
	});

	constructor(
		public text: UnnamedNbtTag
	) {
		super();
	}

}
