// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State } from '../../types';

export class ClientboundSetHealthPacket extends DripleafPacket {
	static readonly id = 0x68;
	static readonly state = State.Play;
	static readonly direction = Direction.Clientbound;

	override readonly id = ClientboundSetHealthPacket.id;
	override readonly state = ClientboundSetHealthPacket.state;
	override readonly direction = ClientboundSetHealthPacket.direction;

	constructor(
		public health: number,
		public food: number,
		public saturation: number
	) {
		super();
	}

	write(writer: PacketWriter) {
		writer.writeFloat(this.health);
		writer.writeVarInt(this.food);
		writer.writeFloat(this.saturation);
	}

	static read(reader: PacketReader): ClientboundSetHealthPacket {
		const health = reader.readFloat();
		const food = reader.readVarInt();
		const saturation = reader.readFloat();
		return new ClientboundSetHealthPacket(health, food, saturation);
	}
}