// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundSetObjectivePacket extends DripleafPacket {
	static readonly codec = packetCodec<ClientboundSetObjectivePacket>({
		encode(writer: PacketWriter, value: ClientboundSetObjectivePacket) {
			throw new Error("TODO: implement codec encode");
		},
		decode(reader: PacketReader): ClientboundSetObjectivePacket {
			throw new Error("TODO: implement codec decode");
		},
	});

	constructor(
		// todo
	) {
		super();
	}

}
