// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { type PacketReader, type PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export type BlockChangeData = {
	position: number;
	blockStateId: number;
};

export class ClientboundSectionBlocksUpdatePacket extends DripleafPacket {
	static readonly codec = packetCodec({
		encode(writer: PacketWriter, value: ClientboundSectionBlocksUpdatePacket) {
			writer.writeLong(packSectionPos(value.sectionX, value.sectionY, value.sectionZ));
			writer.writeVarInt(value.blocks.length);
			for (const block of value.blocks)
				writer.writeVarLong((BigInt(block.blockStateId) << 12n) | BigInt(block.position & 0xfff));
		},
		decode(reader: PacketReader): ClientboundSectionBlocksUpdatePacket {
			const { x: sectionX, y: sectionY, z: sectionZ } = unpackSectionPos(reader.readLong());
			const count = reader.readVarInt();
			const blocks: BlockChangeData[] = [];
			for (let i = 0; i < count; i++) {
				const packed = reader.readVarLong();
				blocks.push({ position: Number(packed & 4095n), blockStateId: Number(packed >> 12n) });
			}
			return new ClientboundSectionBlocksUpdatePacket(sectionX, sectionY, sectionZ, blocks);
		},
	});

	constructor(
		public sectionX: number,
		public sectionY: number,
		public sectionZ: number,
		public blocks: BlockChangeData[],
	) {
		super();
	}

}

function packSectionPos(x: number, y: number, z: number): bigint {
	return ((BigInt(x & 0x3fffff) << 42n) | (BigInt(z & 0x3fffff) << 20n) | BigInt(y & 0xfffff));
}

function unpackSectionPos(value: bigint): { x: number; y: number; z: number } {
	const x = signExtend(Number((value >> 42n) & 0x3fffffn), 22);
	const z = signExtend(Number((value >> 20n) & 0x3fffffn), 22);
	const y = signExtend(Number(value & 0xfffffn), 20);
	return { x, y, z };
}

function signExtend(value: number, bits: number): number {
	const shift = 32 - bits;
	return (value << shift) >> shift;
}
