// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State } from '../../types';

export class ClientboundSetBorderLerpSizePacket extends DripleafPacket {
	static readonly id = 0x59;
	static readonly state = State.Play;
	static readonly direction = Direction.Clientbound;

	override readonly id = ClientboundSetBorderLerpSizePacket.id;
	override readonly state = ClientboundSetBorderLerpSizePacket.state;
	override readonly direction = ClientboundSetBorderLerpSizePacket.direction;

	constructor(
		public oldSize: number,
		public newSize: number,
		public lerpTime: bigint
	) {
		super();
	}

	write(writer: PacketWriter) {
		writer.writeDouble(this.oldSize);
		writer.writeDouble(this.newSize);
		writer.writeVarLong(this.lerpTime);
	}

	static read(reader: PacketReader): ClientboundSetBorderLerpSizePacket {
		const oldSize = reader.readDouble();
		const newSize = reader.readDouble();
		const lerpTime = reader.readVarLong();
		return new ClientboundSetBorderLerpSizePacket(oldSize, newSize, lerpTime);
	}
}