// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

export { ClientboundShowDialogPacket } from '../configuration/c_show_dialog_packet'