// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs, type Holder } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import { SoundSource } from '../common';
import type { SoundEventValue } from '@dripleaf/core';
import { soundHolderCodec } from '../../datatypes';

export class ClientboundSoundPacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundSoundPacket, {
		sound: soundHolderCodec,
		source: Codecs.byteEnum(SoundSource),
		x: Codecs.int,
		y: Codecs.int,
		z: Codecs.int,
		volume: Codecs.float,
		pitch: Codecs.float,
		seed: Codecs.long
	});

	constructor(
		public sound: Holder<string, SoundEventValue>,
		public source: SoundSource,
		public x: number,
		public y: number,
		public z: number,
		public volume: number,
		public pitch: number,
		public seed: bigint
	) {
		super();
	}
}