// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs, type Holder } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import type { SoundEventValue } from '@dripleaf/core';
import { soundHolderCodec } from '../../datatypes';
import { SoundSource } from '../common';

export class ClientboundSoundEntityPacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundSoundEntityPacket, {
		sound: soundHolderCodec,
		source: Codecs.byteEnum(SoundSource),
		id: Codecs.varInt,
		volume: Codecs.float,
		pitch: Codecs.float,
		seed: Codecs.long
	})

	constructor(
		public sound: Holder<string, SoundEventValue>,
		public source: SoundSource,
		public id: number,
		public volume: number,
		public pitch: number,
		public seed: bigint
	) {
		super();
	}
}