// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import type { Identifier } from '@dripleaf/registry';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import type { SoundSource } from '../common';

export class ClientboundStopSoundPacket extends DripleafPacket {
	static readonly codec = packetCodec<ClientboundStopSoundPacket>({
		encode(writer, value) {
			let flags = 0
			if (value.source != null) flags |= 1
			if (value.name != null) flags |= 2
			writer.writeByte(flags)
			if (value.source != null) writer.writeByte(value.source)
			if (value.name != null) writer.writeIdentifier(value.name)
		},
		decode(reader) {
			const flags = reader.readByte()
			const source = (flags & 1) !== 0 ? reader.readByte() as SoundSource : null
			const name = (flags & 2) !== 0 ? reader.readIdentifier() : null
			return new ClientboundStopSoundPacket(source, name)
		},
	});

	constructor(
		public source: SoundSource | null,
		public name: Identifier | null,
	) {
		super();
	}
}