// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { ChatComponentCodec } from '../../datatypes';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import type { ChatComponent } from '@dripleaf/chat';

export class ClientboundSystemChatPacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundSystemChatPacket, {
		content: ChatComponentCodec,
		overlay: Codecs.bool,
	});

	constructor(
		public content: ChatComponent,
		public overlay: boolean,
	) {
		super();
	}

}
