// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PositionMoveRotation, RelativeMovements } from '@dripleaf/core';
import { PositionMoveRotationCodec, RelativeMovementsCodec } from '../../datatypes';
import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundTeleportEntityPacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundTeleportEntityPacket, {
		id: Codecs.varInt,
		change: PositionMoveRotationCodec,
		relatives: RelativeMovementsCodec,
		onGround: Codecs.bool
	});

	constructor(
		public id: number,
		public change: PositionMoveRotation,
		public relatives: RelativeMovements,
		public onGround: boolean,
	) {
		super();
	}
}