// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import type { TagNetworkPayload } from '@dripleaf/core';
import { TagNetworkPayloadCodec } from '../../datatypes';

export class ClientboundUpdateTagsPacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundUpdateTagsPacket, {
		tags: Codecs.map(Codecs.string(), TagNetworkPayloadCodec),
	});

	constructor(
		public tags: Map<string, TagNetworkPayload>,
	) {
		super();
	}

}
