// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { type PacketReader, type PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundWaypointPacket extends DripleafPacket {
	static readonly codec = packetCodec({
		encode(writer: PacketWriter, value: ClientboundWaypointPacket) {
			writer.writeVarInt(value.operation);
			writer.writeBytes(value.data);
		},
		decode(reader: PacketReader): ClientboundWaypointPacket {
			const operation = reader.readVarInt();
			const data = reader.readRemaining();
			return new ClientboundWaypointPacket(operation, data);
		},
	});

	constructor(
		public operation: number,
		public data: Uint8Array,
	) {
		super();
	}
}
