// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State } from '../../types';

export class ServerboundBundleItemSelectedPacket extends DripleafPacket {
	static readonly id = 0x03;
	static readonly state = State.Play;
	static readonly direction = Direction.Serverbound;

	override readonly id = ServerboundBundleItemSelectedPacket.id;
	override readonly state = ServerboundBundleItemSelectedPacket.state;
	override readonly direction = ServerboundBundleItemSelectedPacket.direction;

	constructor(
		// todo
	) {
		super();
	}

	write(writer: PacketWriter) {
		// todo
	}

	static read(reader: PacketReader): ServerboundBundleItemSelectedPacket {
		// todo
	}
}