// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { DebugSubscription } from '@dripleaf/registry';
import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ServerboundDebugSubscriptionRequestPacket extends DripleafPacket {
	static readonly codec = packetCodec(ServerboundDebugSubscriptionRequestPacket, {
		subscriptions: Codecs.array(Codecs.varIntEnum(DebugSubscription)),
	});

	constructor(
		public subscriptions: DebugSubscription[],
	) {
		super();
	}

}
