// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ServerboundEditBookPacket extends DripleafPacket {
	static readonly codec = packetCodec(ServerboundEditBookPacket, {
		slot: Codecs.varInt,
		pages: Codecs.array(Codecs.string()),
		title: Codecs.prefixedOptional(Codecs.string()),
	});

	constructor(
		public slot: number,
		public pages: string[],
		public title: string | null,
	) {
		super();
	}

}
