// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { InteractionHand } from '../../types';
import { Codecs, type PacketReader, type PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import type { Vec3 } from 'vec3';

export class ServerboundInteractPacket extends DripleafPacket {
	static readonly codec = packetCodec({
		encode(writer: PacketWriter, value: ServerboundInteractPacket) {
			writer.writeVarInt(value.entityId);
			Codecs.varIntEnum(InteractionHand).encode(writer, value.hand);
			writer.writeLpVec3(value.location);
			writer.writeBoolean(value.usingSecondaryAction);
		},
		decode(reader: PacketReader): ServerboundInteractPacket {
			return new ServerboundInteractPacket(
				reader.readVarInt(),
				Codecs.varIntEnum(InteractionHand).decode(reader),
				reader.readLpVec3(),
				reader.readBoolean(),
			);
		},
	});

	constructor(
		public entityId: number,
		public hand: InteractionHand,
		public location: Vec3,
		public usingSecondaryAction: boolean,
	) {
		super();
	}

}
