// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { packetCodec } from '../DripleafPacket';
import { type PacketReader, type PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';

function packFlags(onGround: boolean, horizontalCollision: boolean): number {
	return (onGround ? 1 : 0) | (horizontalCollision ? 2 : 0);
}

export class ServerboundMovePlayerPosPacket extends DripleafPacket {
	static readonly codec = packetCodec({
		encode(writer: PacketWriter, value: ServerboundMovePlayerPosPacket) {
			writer.writeDouble(value.x);
			writer.writeDouble(value.y);
			writer.writeDouble(value.z);
			writer.writeUnsignedByte(packFlags(value.onGround, value.horizontalCollision));
		},
		decode(reader: PacketReader): ServerboundMovePlayerPosPacket {
			const x = reader.readDouble();
			const y = reader.readDouble();
			const z = reader.readDouble();
			const flags = reader.readUnsignedByte();
			return new ServerboundMovePlayerPosPacket(x, y, z, (flags & 1) !== 0, (flags & 2) !== 0);
		},
	});

	constructor(
		public x: number,
		public y: number,
		public z: number,
		public onGround: boolean,
		public horizontalCollision: boolean,
	) {
		super();
	}

}
