// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { packetCodec } from '../DripleafPacket';
import { type PacketReader, type PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';

function packFlags(onGround: boolean, horizontalCollision: boolean): number {
	return (onGround ? 1 : 0) | (horizontalCollision ? 2 : 0);
}

export class ServerboundMovePlayerStatusOnlyPacket extends DripleafPacket {
	static readonly codec = packetCodec({
		encode(writer: PacketWriter, value: ServerboundMovePlayerStatusOnlyPacket) {
			writer.writeUnsignedByte(packFlags(value.onGround, value.horizontalCollision));
		},
		decode(reader: PacketReader): ServerboundMovePlayerStatusOnlyPacket {
			const flags = reader.readUnsignedByte();
			return new ServerboundMovePlayerStatusOnlyPacket((flags & 1) !== 0, (flags & 2) !== 0);
		},
	});

	constructor(
		public onGround: boolean,
		public horizontalCollision: boolean,
	) {
		super();
	}

}
