// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ServerboundSetCommandMinecartPacket extends DripleafPacket {
	static readonly codec = packetCodec(ServerboundSetCommandMinecartPacket, {
		entity: Codecs.varInt,
		command: Codecs.string(),
		trackOutput: Codecs.bool,
	});

	constructor(
		public entity: number,
		public command: string,
		public trackOutput: boolean
	) {
		super();
	}

}
