// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import { BlockPos } from '@dripleaf/core';
import { BlockPosCodec } from '../../datatypes/BlockPos';
import type { Identifier } from '@dripleaf/registry';

export class ServerboundSetJigsawBlockPacket extends DripleafPacket {
	static readonly codec = packetCodec(ServerboundSetJigsawBlockPacket, {
		pos: BlockPosCodec,
		name: Codecs.identifier,
		target: Codecs.identifier,
		pool: Codecs.identifier,
		finalState: Codecs.string(),
		joint: Codecs.string(),
		selectionPriority: Codecs.varInt,
		placementPriority: Codecs.varInt,
	});

	constructor(
		public pos: BlockPos,
		public name: Identifier,
		public target: Identifier,
		public pool: Identifier,
		public finalState: string,
		public joint: string,
		public selectionPriority: number,
		public placementPriority: number,
	) {
		super();
	}

}
