// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { ItemStackCodec } from '../common';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ServerboundSetCreativeModeSlotPacket extends DripleafPacket {
	static readonly codec = packetCodec(ServerboundSetCreativeModeSlotPacket, {
		slotNum: Codecs.unsignedShort,
		itemStack: ItemStackCodec,
	});

	constructor(
		public slotNum: number,
		public itemStack: object,
	) {
		super();
	}

}
