// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import type { Identifier } from '@dripleaf/registry';
import { Codecs, type PacketReader, type PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export enum SeenAdvancementsAction {
	OpenedTab = 0,
	ClosedScreen = 1,
}

export class ServerboundSeenAdvancementsPacket extends DripleafPacket {
	static readonly codec = packetCodec({
		encode(writer: PacketWriter, value: ServerboundSeenAdvancementsPacket) {
			Codecs.varIntEnum(SeenAdvancementsAction).encode(writer, value.action);
			if (value.action === SeenAdvancementsAction.OpenedTab && value.tab)
				writer.writeIdentifier(value.tab);
		},
		decode(reader: PacketReader): ServerboundSeenAdvancementsPacket {
			const action = Codecs.varIntEnum(SeenAdvancementsAction).decode(reader);
			const tab = action === SeenAdvancementsAction.OpenedTab ? reader.readIdentifier() : null;
			return new ServerboundSeenAdvancementsPacket(action, tab);
		},
	});

	constructor(
		public action: SeenAdvancementsAction,
		public tab: Identifier | null,
	) {
		super();
	}

}
