// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { BlockPos } from '@dripleaf/core';
import { BlockPosCodec } from '../../datatypes/BlockPos';
import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ServerboundSignUpdatePacket extends DripleafPacket {
	static readonly codec = packetCodec(ServerboundSignUpdatePacket, {
		pos: BlockPosCodec,
		isFrontText: Codecs.bool,
		lines: Codecs.array(Codecs.string()),
	});

	constructor(
		public pos: BlockPos,
		public isFrontText: boolean,
		public lines: string[],
	) {
		super();
	}

}
