// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { BlockPos } from '@dripleaf/core';
import { BlockPosCodec } from '../../datatypes/BlockPos';
import { type PacketReader, type PacketWriter, Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ServerboundSignUpdatePacket extends DripleafPacket {
	static readonly codec = packetCodec({
		encode(writer: PacketWriter, value: ServerboundSignUpdatePacket) {
			BlockPosCodec.encode(writer, value.pos);
			writer.writeBoolean(value.isFrontText);
			for (const line of value.lines) {
				writer.writeString(line, 384);
			}
		},
		decode(reader: PacketReader): ServerboundSignUpdatePacket {
			return new ServerboundSignUpdatePacket(
				BlockPosCodec.decode(reader),
				reader.readBoolean(),
				[
					reader.readString(384),
					reader.readString(384),
					reader.readString(384),
					reader.readString(384),
				],
			);
		},
	});

	constructor(
		public pos: BlockPos,
		public isFrontText: boolean,
		public lines: [string, string, string, string],
	) {
		super();
	}

}
