// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { BlockPos } from '@dripleaf/core';
import { BlockPosCodec } from '../../datatypes/BlockPos';
import { Codecs, type PacketReader, type PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import { Direction, InteractionHand } from '../../types';
import type { Vec3 } from 'vec3';

export class ServerboundUseItemOnPacket extends DripleafPacket {
	static readonly codec = packetCodec({
		encode(writer: PacketWriter, value: ServerboundUseItemOnPacket) {
			writer.writeVarInt(value.hand);
			BlockPosCodec.encode(writer, value.blockHit.blockPos)
			Codecs.varIntEnum(Direction).encode(writer, value.blockHit.direction)
			writer.writeVec3d(value.blockHit.location)
			writer.writeBoolean(value.blockHit.inside)
			writer.writeBoolean(value.blockHit.worldBorder)
			writer.writeVarInt(value.seq)
		},
		decode(reader: PacketReader): ServerboundUseItemOnPacket {
			return new ServerboundUseItemOnPacket(
				reader.readVarInt(),
				{
					blockPos: BlockPosCodec.decode(reader),
					direction: Codecs.varIntEnum(Direction).decode(reader),
					location: reader.readVec3d(),
					inside: reader.readBoolean(),
					worldBorder: reader.readBoolean(),
				},
				reader.readVarInt(),
			)
		},
	})

	constructor(
		public hand: InteractionHand,
		public blockHit: { blockPos: BlockPos; direction: Direction; location: Vec3; inside: boolean; worldBorder: boolean },
		public seq: number,
	) {
		super();
	}

}
