// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State } from '../../types';

export class ServerboundIntentionPacket extends DripleafPacket {
	static readonly id = 0x00;
	static readonly state = State.Handshake;
	static readonly direction = Direction.Serverbound;

	override readonly id = ServerboundIntentionPacket.id;
	override readonly state = ServerboundIntentionPacket.state;
	override readonly direction = ServerboundIntentionPacket.direction;

	constructor(
		public protocolVersion: number,
		public serverAddress: string,
		public serverPort: number,
		public intention: number
	) {
		super();
	}

	write(writer: PacketWriter) {
		writer.writeVarInt(this.protocolVersion);
		writer.writeString(this.serverAddress, 255);
		writer.writeUnsignedShort(this.serverPort);
		writer.writeVarInt(this.intention);
	}

	static read(reader: PacketReader): ServerboundIntentionPacket {
		const protocolVersion = reader.readVarInt();
		const serverAddress = reader.readString(255);
		const serverPort = reader.readUnsignedShort();
		const intention = reader.readVarInt();
		return new ServerboundIntentionPacket(protocolVersion, serverAddress, serverPort, intention);
	}
}