// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import { ClientIntention } from '../../types';

export class ServerboundIntentionPacket extends DripleafPacket {
	static readonly codec = packetCodec(ServerboundIntentionPacket, {
		protocolVersion: Codecs.varInt,
		serverAddress: Codecs.string(255),
		serverPort: Codecs.unsignedShort,
		intention: Codecs.varInt,
	});

	constructor(
		public protocolVersion: number,
		public serverAddress: string,
		public serverPort: number,
		public intention: ClientIntention
	) {
		super();
	}
}