// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundCodeOfConductPacket extends DripleafPacket {
	static readonly codec = packetCodec<ClientboundCodeOfConductPacket>({
		encode(writer: PacketWriter, value: ClientboundCodeOfConductPacket) {
		writer.writeString(value.codeOfConduct);
		},
		decode(reader: PacketReader): ClientboundCodeOfConductPacket {
		const codeOfConduct = reader.readString();
		return new ClientboundCodeOfConductPacket(codeOfConduct);
		},
	});

	constructor(
		public codeOfConduct: string,
	) {
		super();
	}

}
