// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Direction, State } from '../../types';
import { GlowstonePacket } from '../../packet';
import { PacketReader, PacketWriter } from '../../buffer';

class ClientboundCodeOfConductPacket extends GlowstonePacket {
	override id = 0x13;
	override state = State.Configuration;
	override direction = Direction.Clientbound;

	constructor(
		public codeOfConduct: string,
	) {
		super();
	}

	serialize() {
		const writer = new PacketWriter();
		writer.writeString(this.codeOfConduct);
		return writer.finish();
	}

	static override deserialize(bytes: Uint8Array): ClientboundCodeOfConductPacket {
		const reader = new PacketReader(bytes);
		const codeOfConduct = reader.readString();
		return new ClientboundCodeOfConductPacket(codeOfConduct);
	}
}

export { ClientboundCodeOfConductPacket };