// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

type DetailEntry = {
	title: string;
	description: string;
}

export class ClientboundCustomReportDetailsPacket extends DripleafPacket {
	static readonly codec = packetCodec<ClientboundCustomReportDetailsPacket>({
		encode(writer: PacketWriter, value: ClientboundCustomReportDetailsPacket) {
		writer.writeArray(value.details, (detail) => {
			writer.writeString(detail.title, 128);
			writer.writeString(detail.description, 4096);
		});
		},
		decode(reader: PacketReader): ClientboundCustomReportDetailsPacket {
		const details = reader.readArray(() => {
			const title = reader.readString(128);
			const description = reader.readString(4096);
			return { title, description };
		});
		return new ClientboundCustomReportDetailsPacket(details);
		},
	});

	constructor(
		public details: DetailEntry[],
	) {
		super();
	}

}
