// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State } from '../../types';

export class ClientboundFinishConfigurationPacket extends DripleafPacket {
	static readonly id = 0x03;
	static readonly state = State.Configuration;
	static readonly direction = Direction.Clientbound;

	override readonly id = ClientboundFinishConfigurationPacket.id;
	override readonly state = ClientboundFinishConfigurationPacket.state;
	override readonly direction = ClientboundFinishConfigurationPacket.direction;

	constructor() {
		super();
	}

	write(writer: PacketWriter) {
		return new Uint8Array();
	}

	static read(reader: PacketReader): ClientboundFinishConfigurationPacket {
		return new ClientboundFinishConfigurationPacket();
	}
}