// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundFinishConfigurationPacket extends DripleafPacket {
	static readonly codec = packetCodec<ClientboundFinishConfigurationPacket>({
		encode(writer: PacketWriter, value: ClientboundFinishConfigurationPacket) {
		return new Uint8Array();
		},
		decode(reader: PacketReader): ClientboundFinishConfigurationPacket {
		return new ClientboundFinishConfigurationPacket();
		},
	});

	constructor() {
		super();
	}

}
