// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import type { UnnamedNbtTag } from '@dripleaf/nbt';

type RegistryEntry = {
	entryId: string;
	data: UnnamedNbtTag | null;
}

export class ClientboundRegistryDataPacket extends DripleafPacket {
	static readonly codec = packetCodec<ClientboundRegistryDataPacket>({
		encode(writer: PacketWriter, value: ClientboundRegistryDataPacket) {
		writer.writeString(value.registryId);
		writer.writeArray(value.entries, (entry) => {
			writer.writeString(entry.entryId);
			writer.writePrefixedOptional(entry.data, (v) => writer.writeNbt(v));
		});
		},
		decode(reader: PacketReader): ClientboundRegistryDataPacket {
		const registryId = reader.readString();
		const entries = reader.readArray(() => {
			const entryId = reader.readString();
			const data = reader.readPrefixedOptional(() => reader.readNbt());
			return { entryId, data };
		});
		return new ClientboundRegistryDataPacket(registryId, entries);
		},
	});

	constructor(
		public registryId: string,
		public entries: RegistryEntry[]
	) {
		super();
	}

}
