// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State } from '../../types';
import type { UnnamedNbtTag } from '@dripleaf/nbt';

type RegistryEntry = {
	entryId: string;
	data: UnnamedNbtTag | null;
}

export class ClientboundRegistryDataPacket extends DripleafPacket {
	static readonly id = 0x07;
	static readonly state = State.Configuration;
	static readonly direction = Direction.Clientbound;

	override readonly id = ClientboundRegistryDataPacket.id;
	override readonly state = ClientboundRegistryDataPacket.state;
	override readonly direction = ClientboundRegistryDataPacket.direction;

	constructor(
		public registryId: string,
		public entries: RegistryEntry[]
	) {
		super();
	}

	write(writer: PacketWriter) {
		writer.writeString(this.registryId);
		writer.writeArray(this.entries, (entry) => {
			writer.writeString(entry.entryId);
			writer.writePrefixedOptional(entry.data, (v) => writer.writeNbt(v));
		});
	}

	static read(reader: PacketReader): ClientboundRegistryDataPacket {
		const registryId = reader.readString();
		const entries = reader.readArray(() => {
			const entryId = reader.readString();
			const data = reader.readPrefixedOptional(() => reader.readNbt());
			return { entryId, data };
		});
		return new ClientboundRegistryDataPacket(registryId, entries);
	}
}