// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundResetChatPacket extends DripleafPacket {
	static readonly codec = packetCodec<ClientboundResetChatPacket>({
		encode(writer: PacketWriter, value: ClientboundResetChatPacket) {
		return new Uint8Array();
		},
		decode(reader: PacketReader): ClientboundResetChatPacket {
		return new ClientboundResetChatPacket();
		},
	});

	constructor() {
		super();
	}

}
