// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { codec, Codecs, type PacketReader, type PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import type { UnnamedNbtTag } from '@dripleaf/nbt';

type RegistryEntry = {
	entryId: string;
	data: UnnamedNbtTag | null;
}

const RegistryEntryCodec = codec<RegistryEntry>({
	encode(writer: PacketWriter, value: RegistryEntry) {
		writer.writeString(value.entryId);
		writer.writePrefixedOptional(value.data, v => writer.writeNbt(v));
	},
	decode(reader: PacketReader): RegistryEntry {
		const entryId = reader.readString();
		const data = reader.readPrefixedOptional(() => reader.readNbt());
		return { entryId, data };
	},
});

export class ClientboundRegistryDataPacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundRegistryDataPacket, {
		registryId: Codecs.string(),
		entries: Codecs.array(RegistryEntryCodec),
	});

	constructor(
		public registryId: string,
		public entries: RegistryEntry[]
	) {
		super();
	}
}