// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Direction, State } from '../../types';
import { GlowstonePacket } from '../../packet';
import { PacketReader, PacketWriter } from '../../buffer';
import type { UUID } from 'node:crypto';

class ClientboundResourcePackPopPacket extends GlowstonePacket {
	override id = 0x08;
	override state = State.Configuration;
	override direction = Direction.Clientbound;

	constructor(
		public uuid?: UUID | null,
	) {
		super();
	}

	serialize() {
		const writer = new PacketWriter();
		writer.writePrefixedOptional(this.uuid, (v) => writer.writeUUID(v));
		return writer.finish();
	}

	static override deserialize(bytes: Uint8Array): ClientboundResourcePackPopPacket {
		const reader = new PacketReader(bytes);
		const uuid = reader.readPrefixedOptional(() => reader.readUUID());
		return new ClientboundResourcePackPopPacket(uuid);
	}
}

export { ClientboundResourcePackPopPacket };