// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State } from '../../types';
import type { UUID } from 'node:crypto';

export class ClientboundResourcePackPopPacket extends DripleafPacket {
	static readonly id = 0x08;
	static readonly state = State.Configuration;
	static readonly direction = Direction.Clientbound;

	override readonly id = ClientboundResourcePackPopPacket.id;
	override readonly state = ClientboundResourcePackPopPacket.state;
	override readonly direction = ClientboundResourcePackPopPacket.direction;

	constructor(
		public uuid?: UUID | null,
	) {
		super();
	}

	write(writer: PacketWriter) {
		writer.writePrefixedOptional(this.uuid, (v) => writer.writeUUID(v));
	}

	static read(reader: PacketReader): ClientboundResourcePackPopPacket {
		const uuid = reader.readPrefixedOptional(() => reader.readUUID());
		return new ClientboundResourcePackPopPacket(uuid);
	}
}