// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import type { UUID } from 'node:crypto';

export class ClientboundResourcePackPopPacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundResourcePackPopPacket, {
		uuid: Codecs.prefixedOptional(Codecs.uuid),
	});

	constructor(
		public uuid: UUID | null,
	) {
		super();
	}

}
