// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { ChatComponentCodec } from '../../datatypes';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import type { ChatComponent } from '@dripleaf/chat';
import type { UUID } from 'node:crypto';

export class ClientboundResourcePackPushPacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundResourcePackPushPacket, {
		uuid: Codecs.uuid,
		url: Codecs.string(),
		hash: Codecs.string(),
		forced: Codecs.bool,
		promptMessage: Codecs.prefixedOptional(ChatComponentCodec),
	});

	constructor(
		public uuid: UUID,
		public url: string,
		public hash: string,
		public forced: boolean,
		public promptMessage: ChatComponent | null
	) {
		super();
	}
}