// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State } from '../../types';

export class ClientboundResetChatPacket extends DripleafPacket {
	static readonly id = 0x06;
	static readonly state = State.Configuration;
	static readonly direction = Direction.Clientbound;

	override readonly id = ClientboundResetChatPacket.id;
	override readonly state = ClientboundResetChatPacket.state;
	override readonly direction = ClientboundResetChatPacket.direction;

	constructor() {
		super();
	}

	write(writer: PacketWriter) {
		return new Uint8Array();
	}

	static read(reader: PacketReader): ClientboundResetChatPacket {
		return new ClientboundResetChatPacket();
	}
}