// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Direction, State } from '../../types';
import { GlowstonePacket } from '../../packet';
import { PacketReader, PacketWriter } from '../../buffer';
import type { PackEntry } from '../common';

class ClientboundSelectKnownPacksPacket extends GlowstonePacket {
	override id = 0x0e;
	override state = State.Configuration;
	override direction = Direction.Clientbound;

	constructor(
		public knownPacks: PackEntry[],
	) {
		super();
	}

	serialize() {
		const writer = new PacketWriter();
		writer.writeArray(this.knownPacks, (pack) => {
			writer.writeString(pack.namespace);
			writer.writeString(pack.id);
			writer.writeVarInt(pack.version);
		});
		return writer.finish();
	}

	static override deserialize(bytes: Uint8Array): ClientboundSelectKnownPacksPacket {
		const reader = new PacketReader(bytes);
		const knownPacks = reader.readArray(() => {
			const namespace = reader.readString();
			const id = reader.readString();
			const version = reader.readVarInt();
			return { namespace, id, version };
		});
		return new ClientboundSelectKnownPacksPacket(knownPacks);
	}
}

export { ClientboundSelectKnownPacksPacket };