// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import { ServerLinkType, type ServerLink } from '../common';
import type { UnnamedNbtTag } from '@dripleaf/nbt';

export class ClientboundServerLinksPacket extends DripleafPacket {
	static readonly codec = packetCodec<ClientboundServerLinksPacket>({
		encode(writer: PacketWriter, value: ClientboundServerLinksPacket) {
		writer.writeArray(value.links, (link) => {
			writer.writeEither<ServerLinkType, UnnamedNbtTag>(
				link.label,
				(label) => writer.writeVarInt(label),
				(label) => writer.writeNbt(label)
			);
			writer.writeString(link.url);
		});
		},
		decode(reader: PacketReader): ClientboundServerLinksPacket {
		const links = reader.readArray(() => {
			const label = reader.readEither<ServerLinkType, UnnamedNbtTag>(
				() => reader.readVarInt(),
				() => reader.readNbt()
			);
			const url = reader.readString();
			return { label, url };
		});
		return new ClientboundServerLinksPacket(links);
		},
	});

	constructor(
		public links: ServerLink[]
	) {
		super();
	}

}
