// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State } from '../../types';

export class ClientboundServerLinksPacket extends DripleafPacket {
	static readonly id = 0x10;
	static readonly state = State.Configuration;
	static readonly direction = Direction.Clientbound;

	override readonly id = ClientboundServerLinksPacket.id;
	override readonly state = ClientboundServerLinksPacket.state;
	override readonly direction = ClientboundServerLinksPacket.direction;

	constructor(
		// todo: waiting on nbt
	) {
		super();
	}

	write(writer: PacketWriter) {
		// todo
	}

	static read(reader: PacketReader): ClientboundServerLinksPacket {
		// todo
	}
}