// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import type { Dialog } from '@dripleaf/core';
import { dialogHolderCodec } from '../../datatypes';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import type { Holder } from '../../buffer';

export class ClientboundShowDialogPacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundShowDialogPacket, {
		dialog: dialogHolderCodec,
	});

	constructor(
		public dialog: Holder<string, Dialog>,
	) {
		super();
	}
}