// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State } from '../../types';

export class ClientboundShowDialogPacket extends DripleafPacket {
	static readonly id = 0x12;
	static readonly state = State.Configuration;
	static readonly direction = Direction.Clientbound;

	override readonly id = ClientboundShowDialogPacket.id;
	override readonly state = ClientboundShowDialogPacket.state;
	override readonly direction = ClientboundShowDialogPacket.direction;

	constructor(
		// todo: waiting on nbt
	) {
		super();
	}

	write(writer: PacketWriter) {
		// todo
	}

	static read(reader: PacketReader): ClientboundShowDialogPacket {
		// todo
	}
}