// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State } from '../../types';

export class ClientboundTransferPacket extends DripleafPacket {
	static readonly id = 0x0b;
	static readonly state = State.Configuration;
	static readonly direction = Direction.Clientbound;

	override readonly id = ClientboundTransferPacket.id;
	override readonly state = ClientboundTransferPacket.state;
	override readonly direction = ClientboundTransferPacket.direction;

	constructor(
		public host: string,
		public port: number,
	) {
		super();
	}

	write(writer: PacketWriter) {
		writer.writeString(this.host);
		writer.writeVarInt(this.port);
	}

	static read(reader: PacketReader): ClientboundTransferPacket {
		const host = reader.readString();
		const port = reader.readVarInt();
		return new ClientboundTransferPacket(host, port);
	}
}