// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Direction, State } from '../../types';
import { GlowstonePacket } from '../../packet';
import { PacketReader, PacketWriter } from '../../buffer';

class ClientboundUpdateEnabledFeaturesPacket extends GlowstonePacket {
	override id = 0x0c;
	override state = State.Configuration;
	override direction = Direction.Clientbound;

	constructor(
		public featureFlags: string[]
	) {
		super();
	}

	serialize() {
		const writer = new PacketWriter();
		writer.writeArray(this.featureFlags, (v) => writer.writeString(v));
		return writer.finish();
	}

	static override deserialize(bytes: Uint8Array): ClientboundUpdateEnabledFeaturesPacket {
		const reader = new PacketReader(bytes);
		const featureFlags = reader.readArray(() => reader.readString());
		return new ClientboundUpdateEnabledFeaturesPacket(featureFlags);
	}
}

export { ClientboundUpdateEnabledFeaturesPacket };