// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State } from '../../types';

export class ClientboundUpdateEnabledFeaturesPacket extends DripleafPacket {
	static readonly id = 0x0c;
	static readonly state = State.Configuration;
	static readonly direction = Direction.Clientbound;

	override readonly id = ClientboundUpdateEnabledFeaturesPacket.id;
	override readonly state = ClientboundUpdateEnabledFeaturesPacket.state;
	override readonly direction = ClientboundUpdateEnabledFeaturesPacket.direction;

	constructor(
		public featureFlags: string[]
	) {
		super();
	}

	write(writer: PacketWriter) {
		writer.writeArray(this.featureFlags, (v) => writer.writeString(v));
	}

	static read(reader: PacketReader): ClientboundUpdateEnabledFeaturesPacket {
		const featureFlags = reader.readArray(() => reader.readString());
		return new ClientboundUpdateEnabledFeaturesPacket(featureFlags);
	}
}