// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundUpdateEnabledFeaturesPacket extends DripleafPacket {
	static readonly codec = packetCodec<ClientboundUpdateEnabledFeaturesPacket>({
		encode(writer: PacketWriter, value: ClientboundUpdateEnabledFeaturesPacket) {
		writer.writeArray(value.featureFlags, (v) => writer.writeString(v));
		},
		decode(reader: PacketReader): ClientboundUpdateEnabledFeaturesPacket {
		const featureFlags = reader.readArray(() => reader.readString());
		return new ClientboundUpdateEnabledFeaturesPacket(featureFlags);
		},
	});

	constructor(
		public featureFlags: string[]
	) {
		super();
	}

}
