// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State } from '../../types';

type TaggedRegistryEntry = {
	registry: string;
	tags: TagEntry[];
}

type TagEntry = {
	tagName: string;
	values: number[];
}

export class ClientboundUpdateTagsPacket extends DripleafPacket {
	static readonly id = 0x0d;
	static readonly state = State.Configuration;
	static readonly direction = Direction.Clientbound;

	override readonly id = ClientboundUpdateTagsPacket.id;
	override readonly state = ClientboundUpdateTagsPacket.state;
	override readonly direction = ClientboundUpdateTagsPacket.direction;

	constructor(
		public registries: TaggedRegistryEntry[],
	) {
		super();
	}

	write(writer: PacketWriter) {
		writer.writeArray(this.registries, (registry) => {
			writer.writeString(registry.registry);
			writer.writeArray(registry.tags, (tag) => {
				writer.writeString(tag.tagName);
				writer.writeArray(tag.values, (value) => writer.writeVarInt(value));
			});
		});
	}

	static read(reader: PacketReader): ClientboundUpdateTagsPacket {
		const registries = reader.readArray(() => {
			const registry = reader.readString();
			const tags = reader.readArray(() => {
				const tagName = reader.readString();
				const values = reader.readArray(() => reader.readVarInt());
				return { tagName, values };
			});
			return { registry, tags };
		});
		return new ClientboundUpdateTagsPacket(registries);
	}
}