// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ServerboundAcceptCodeOfConductPacket extends DripleafPacket {
	static readonly codec = packetCodec<ServerboundAcceptCodeOfConductPacket>({
		encode(writer: PacketWriter, value: ServerboundAcceptCodeOfConductPacket) {
		return new Uint8Array();
		},
		decode(reader: PacketReader): ServerboundAcceptCodeOfConductPacket {
		return new ServerboundAcceptCodeOfConductPacket();
		},
	});

	constructor() {
		super();
	}

}
