// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State } from '../../types';

export class ServerboundAcceptCodeOfConductPacket extends DripleafPacket {
	static readonly id = 0x09;
	static readonly state = State.Configuration;
	static readonly direction = Direction.Serverbound;

	override readonly id = ServerboundAcceptCodeOfConductPacket.id;
	override readonly state = ServerboundAcceptCodeOfConductPacket.state;
	override readonly direction = ServerboundAcceptCodeOfConductPacket.direction;

	constructor() {
		super();
	}

	write(writer: PacketWriter) {
		return new Uint8Array();
	}

	static read(reader: PacketReader): ServerboundAcceptCodeOfConductPacket {
		return new ServerboundAcceptCodeOfConductPacket();
	}
}