// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

enum ChatMode {
	Enabled = 0,
	CommandsOnly = 1,
	Hidden = 2,
}

enum MainHand {
	Left = 0,
	Right = 1,
}

enum ParticleStatus {
	All = 0,
	Decreased = 1,
	Minimal = 2,
}

export class ServerboundClientInformationPacket extends DripleafPacket {
	static readonly codec = packetCodec<ServerboundClientInformationPacket>({
		encode(writer: PacketWriter, value: ServerboundClientInformationPacket) {
		writer.writeString(value.locale, 16);
		writer.writeByte(value.viewDistance);
		writer.writeVarInt(value.chatMode);
		writer.writeBoolean(value.chatColors);
		writer.writeByte(value.displayedSkinParts);
		writer.writeVarInt(value.mainHand);
		writer.writeBoolean(value.enableTextFiltering);
		writer.writeBoolean(value.allowServerListings);
		writer.writeVarInt(value.particleStatus);
		},
		decode(reader: PacketReader): ServerboundClientInformationPacket {
		const locale = reader.readString(16);
		const viewDistance = reader.readByte();
		const chatMode = reader.readVarInt();
		const chatColors = reader.readBoolean();
		const displayedSkinParts = reader.readByte();
		const mainHand = reader.readVarInt();
		const enableTextFiltering = reader.readBoolean();
		const allowServerListings = reader.readBoolean();
		const particleStatus = reader.readVarInt();
		return new ServerboundClientInformationPacket(locale, viewDistance, chatMode, chatColors, displayedSkinParts, mainHand, enableTextFiltering, allowServerListings, particleStatus);
		},
	});

	constructor(
		public locale: string,
		public viewDistance: number,
		public chatMode: ChatMode,
		public chatColors: boolean,
		public displayedSkinParts: number,
		public mainHand: MainHand,
		public enableTextFiltering: boolean,
		public allowServerListings: boolean,
		public particleStatus: ParticleStatus,
	) {
		super();
	}

}
