// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import { ChatVisibility, HumanoidArm, ParticleStatus, DisplayedSkinPartsCodec } from '../../datatypes';

export class ServerboundClientInformationPacket extends DripleafPacket {
	static readonly codec = packetCodec(ServerboundClientInformationPacket, {
		locale: Codecs.string(),
		viewDistance: Codecs.byte,
		chatMode: Codecs.byteEnum(ChatVisibility),
		chatColors: Codecs.bool,
		displayedSkinParts: DisplayedSkinPartsCodec,
		mainHand: Codecs.byteEnum(HumanoidArm),
		enableTextFiltering: Codecs.bool,
		allowServerListings: Codecs.bool,
		particleStatus: Codecs.byteEnum(ParticleStatus),
	});

	constructor(
		public locale: string,
		public viewDistance: number,
		public chatMode: ChatVisibility,
		public chatColors: boolean,
		public displayedSkinParts: number,
		public mainHand: HumanoidArm,
		public enableTextFiltering: boolean,
		public allowServerListings: boolean,
		public particleStatus: ParticleStatus,
	) {
		super();
	}
}