// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import { ChatVisibility, ChatVisibilityCodec, HumanoidArm, HumanoidArmCodec, ParticleStatus, ParticleStatusCodec, DisplayedSkinPartsCodec } from '../../datatypes';

export class ServerboundClientInformationPacket extends DripleafPacket {
	static readonly codec = packetCodec(ServerboundClientInformationPacket, {
		locale: Codecs.string(),
		viewDistance: Codecs.byte,
		chatMode: ChatVisibilityCodec,
		chatColors: Codecs.bool,
		displayedSkinParts: DisplayedSkinPartsCodec,
		mainHand: HumanoidArmCodec,
		enableTextFiltering: Codecs.bool,
		allowServerListings: Codecs.bool,
		particleStatus: ParticleStatusCodec,
	});

	constructor(
		public locale: string,
		public viewDistance: number,
		public chatMode: ChatVisibility,
		public chatColors: boolean,
		public displayedSkinParts: number,
		public mainHand: HumanoidArm,
		public enableTextFiltering: boolean,
		public allowServerListings: boolean,
		public particleStatus: ParticleStatus,
	) {
		super();
	}
}