// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State } from '../../types';

export class ServerboundCookieResponsePacket extends DripleafPacket {
	static readonly id = 0x01;
	static readonly state = State.Configuration;
	static readonly direction = Direction.Serverbound;

	override readonly id = ServerboundCookieResponsePacket.id;
	override readonly state = ServerboundCookieResponsePacket.state;
	override readonly direction = ServerboundCookieResponsePacket.direction;

	constructor(
		public key: string,
		public payload: Uint8Array
	) {
		super();
	}

	write(writer: PacketWriter) {
		writer.writeString(this.key);
		writer.writeByteArray(this.payload, 5120);
	}

	static read(reader: PacketReader): ServerboundCookieResponsePacket {
		const key = reader.readString();
		const payload = reader.readByteArray(5120);
		return new ServerboundCookieResponsePacket(key, payload);
	}
}