// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ServerboundCookieResponsePacket extends DripleafPacket {
	static readonly codec = packetCodec<ServerboundCookieResponsePacket>({
		encode(writer: PacketWriter, value: ServerboundCookieResponsePacket) {
		writer.writeString(value.key);
		writer.writeByteArray(value.payload, 5120);
		},
		decode(reader: PacketReader): ServerboundCookieResponsePacket {
		const key = reader.readString();
		const payload = reader.readByteArray(5120);
		return new ServerboundCookieResponsePacket(key, payload);
		},
	});

	constructor(
		public key: string,
		public payload: Uint8Array
	) {
		super();
	}

}
