// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { type PacketReader, type PacketWriter, Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ServerboundCustomPayloadPacket extends DripleafPacket {
	static readonly codec = packetCodec({
		encode(writer: PacketWriter, value: ServerboundCustomPayloadPacket) {
			writer.writeIdentifier(value.channel);
			writer.writeBytes(value.data);
		},
		decode(reader: PacketReader): ServerboundCustomPayloadPacket {
			return new ServerboundCustomPayloadPacket(
				reader.readIdentifier(),
				reader.readRemaining(),
			);
		},
	});

	constructor(
		public channel: string,
		public data: Uint8Array,
	) {
		super();
	}
}