// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Direction, State } from '../../types';
import { GlowstonePacket } from '../../packet';
import { PacketReader, PacketWriter } from '../../buffer';

class ServerboundCustomPayloadPacket extends GlowstonePacket {
	override id = 0x02;
	override state = State.Configuration;
	override direction = Direction.Serverbound;

	constructor(
		public channel: string,
		public data: Uint8Array,
	) {
		super();
	}

	serialize() {
		const writer = new PacketWriter();
		writer.writeString(this.channel);
		writer.writeByteArray(this.data);
		return writer.finish();
	}

	static override deserialize(bytes: Uint8Array): ServerboundCustomPayloadPacket {
		const reader = new PacketReader(bytes);
		const channel = reader.readString();
		const data = reader.readByteArray();
		return new ServerboundCustomPayloadPacket(channel, data);
	}
}

export { ServerboundCustomPayloadPacket };