// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ServerboundCustomPayloadPacket extends DripleafPacket {
	static readonly codec = packetCodec<ServerboundCustomPayloadPacket>({
		encode(writer: PacketWriter, value: ServerboundCustomPayloadPacket) {
		writer.writeString(value.channel);
		writer.writeByteArray(value.data);
		},
		decode(reader: PacketReader): ServerboundCustomPayloadPacket {
		const channel = reader.readString();
		const data = reader.readByteArray();
		return new ServerboundCustomPayloadPacket(channel, data);
		},
	});

	constructor(
		public channel: string,
		public data: Uint8Array,
	) {
		super();
	}

}
