// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ServerboundFinishConfigurationPacket extends DripleafPacket {
	static readonly codec = packetCodec<ServerboundFinishConfigurationPacket>({
		encode(writer: PacketWriter, value: ServerboundFinishConfigurationPacket) {
		return new Uint8Array();
		},
		decode(reader: PacketReader): ServerboundFinishConfigurationPacket {
		return new ServerboundFinishConfigurationPacket();
		},
	});

	constructor() {
		super();
	}

}
