// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State } from '../../types';

export class ServerboundKeepAlivePacket extends DripleafPacket {
	static readonly id = 0x04;
	static readonly state = State.Configuration;
	static readonly direction = Direction.Serverbound;

	override readonly id = ServerboundKeepAlivePacket.id;
	override readonly state = ServerboundKeepAlivePacket.state;
	override readonly direction = ServerboundKeepAlivePacket.direction;

	constructor(
		public keepAliveId: bigint
	) {
		super();
	}

	write(writer: PacketWriter) {
		writer.writeLong(this.keepAliveId);
	}

	static read(reader: PacketReader): ServerboundKeepAlivePacket {
		const keepAliveId = reader.readLong();
		return new ServerboundKeepAlivePacket(keepAliveId);
	}
}