// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Direction, State } from '../../types';
import { GlowstonePacket } from '../../packet';
import { PacketReader, PacketWriter } from '../../buffer';

class ServerboundKeepAlivePacket extends GlowstonePacket {
	override id = 0x04;
	override state = State.Configuration;
	override direction = Direction.Serverbound;

	constructor(
		public keepAliveId: bigint
	) {
		super();
	}

	serialize() {
		const writer = new PacketWriter();
		writer.writeLong(this.keepAliveId);
		return writer.finish();
	}

	static override deserialize(bytes: Uint8Array): ServerboundKeepAlivePacket {
		const reader = new PacketReader(bytes);
		const keepAliveId = reader.readLong();
		return new ServerboundKeepAlivePacket(keepAliveId);
	}
}

export { ServerboundKeepAlivePacket };