// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ServerboundPongPacket extends DripleafPacket {
	static readonly codec = packetCodec(ServerboundPongPacket, {
		pingId: Codecs.long,
	});

	constructor(
		public pingId: bigint
	) {
		super();
	}
}