// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Direction, State } from '../../types';
import { GlowstonePacket } from '../../packet';
import { PacketReader, PacketWriter } from '../../buffer';

class ServerboundPongPacket extends GlowstonePacket {
	override id = 0x05;
	override state = State.Configuration;
	override direction = Direction.Serverbound;

	constructor(
		public pingId: bigint
	) {
		super();
	}

	serialize() {
		const writer = new PacketWriter();
		writer.writeLong(this.pingId);
		return writer.finish();
	}

	static override deserialize(bytes: Uint8Array): ServerboundPongPacket {
		const reader = new PacketReader(bytes);
		const pingId = reader.readLong();
		return new ServerboundPongPacket(pingId);
	}
}

export { ServerboundPongPacket };