// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State } from '../../types';

export class ServerboundPongPacket extends DripleafPacket {
	static readonly id = 0x05;
	static readonly state = State.Configuration;
	static readonly direction = Direction.Serverbound;

	override readonly id = ServerboundPongPacket.id;
	override readonly state = ServerboundPongPacket.state;
	override readonly direction = ServerboundPongPacket.direction;

	constructor(
		public pingId: bigint
	) {
		super();
	}

	write(writer: PacketWriter) {
		writer.writeLong(this.pingId);
	}

	static read(reader: PacketReader): ServerboundPongPacket {
		const pingId = reader.readLong();
		return new ServerboundPongPacket(pingId);
	}
}