// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import { KnownPack } from '../../datatypes/KnownPack';

export class ServerboundSelectKnownPacksPacket extends DripleafPacket {
	static readonly codec = packetCodec(ServerboundSelectKnownPacksPacket, {
		knownPacks: Codecs.array(KnownPack.codec),
	});

	constructor(
		public knownPacks: KnownPack[],
	) {
		super();
	}
}