// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State } from '../../types';

export class ClientboundCustomQueryPacket extends DripleafPacket {
	static readonly id = 0x04;
	static readonly state = State.Login;
	static readonly direction = Direction.Clientbound;

	override readonly id = ClientboundCustomQueryPacket.id;
	override readonly state = ClientboundCustomQueryPacket.state;
	override readonly direction = ClientboundCustomQueryPacket.direction;

	constructor(
		public messageId: number,
		public channel: string,
		public data: Uint8Array
	) {
		super();
	}

	write(writer: PacketWriter) {
		writer.writeVarInt(this.messageId);
		writer.writeString(this.channel);
		writer.writeByteArray(this.data);
	}

	static read(reader: PacketReader): ClientboundCustomQueryPacket {
		const messageId = reader.readVarInt();
		const channel = reader.readString();
		const data = reader.readByteArray();
		return new ClientboundCustomQueryPacket(messageId, channel, data);
	}
}