// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs, type PacketReader, type PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundCustomQueryPacket extends DripleafPacket {
	static readonly codec = packetCodec({
		encode(writer: PacketWriter, value: ClientboundCustomQueryPacket) {
			writer.writeVarInt(value.messageId);
			writer.writeIdentifier(value.channel);
			writer.writeBytes(value.data);
		},
		decode(reader: PacketReader): ClientboundCustomQueryPacket {
			return new ClientboundCustomQueryPacket(
				reader.readVarInt(),
				reader.readIdentifier().toString(),
				reader.readRemaining(),
			);
		},
	});

	constructor(
		public messageId: number,
		public channel: string,
		public data: Uint8Array
	) {
		super();
	}
}