// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State } from '../../types';

export class ClientboundHelloPacket extends DripleafPacket {
	static readonly id = 0x01;
	static readonly state = State.Login;
	static readonly direction = Direction.Clientbound;

	override readonly id = ClientboundHelloPacket.id;
	override readonly state = ClientboundHelloPacket.state;
	override readonly direction = ClientboundHelloPacket.direction;

	constructor(
		public serverId: string,
		public publicKey: Uint8Array,
		public verifyToken: Uint8Array,
		public shouldAuthenticate: boolean
	) {
		super();
	}

	write(writer: PacketWriter) {
		writer.writeString(this.serverId, 20);
		writer.writeByteArray(this.publicKey);
		writer.writeByteArray(this.verifyToken);
		writer.writeBoolean(this.shouldAuthenticate);
	}

	static read(reader: PacketReader): ClientboundHelloPacket {
		const serverId = reader.readString(20);
		const publicKey = reader.readByteArray();
		const verifyToken = reader.readByteArray();
		const shouldAuthenticate = reader.readBoolean();
		return new ClientboundHelloPacket(serverId, publicKey, verifyToken, shouldAuthenticate);
	}
}