// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundHelloPacket extends DripleafPacket {
	static readonly codec = packetCodec<ClientboundHelloPacket>({
		encode(writer: PacketWriter, value: ClientboundHelloPacket) {
		writer.writeString(value.serverId, 20);
		writer.writeByteArray(value.publicKey);
		writer.writeByteArray(value.verifyToken);
		writer.writeBoolean(value.shouldAuthenticate);
		},
		decode(reader: PacketReader): ClientboundHelloPacket {
		const serverId = reader.readString(20);
		const publicKey = reader.readByteArray();
		const verifyToken = reader.readByteArray();
		const shouldAuthenticate = reader.readBoolean();
		return new ClientboundHelloPacket(serverId, publicKey, verifyToken, shouldAuthenticate);
		},
	});

	constructor(
		public serverId: string,
		public publicKey: Uint8Array,
		public verifyToken: Uint8Array,
		public shouldAuthenticate: boolean
	) {
		super();
	}

}
