// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundHelloPacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundHelloPacket, {
		serverId: Codecs.string(),
		publicKey: Codecs.byteArray(),
		verifyToken: Codecs.byteArray(),
		shouldAuthenticate: Codecs.bool,
	});

	constructor(
		public serverId: string,
		public publicKey: Uint8Array,
		public verifyToken: Uint8Array,
		public shouldAuthenticate: boolean
	) {
		super();
	}
}