// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State } from '../../types';

export class ClientboundLoginDisconnectPacket extends DripleafPacket {
	static readonly id = 0x00;
	static readonly state = State.Login;
	static readonly direction = Direction.Clientbound;

	override readonly id = ClientboundLoginDisconnectPacket.id;
	override readonly state = ClientboundLoginDisconnectPacket.state;
	override readonly direction = ClientboundLoginDisconnectPacket.direction;

	constructor(
		public reason: Object,
	) {
		super();
	}

	write(writer: PacketWriter) {
		writer.writeString(JSON.stringify(this.reason));
	}

	static read(reader: PacketReader): ClientboundLoginDisconnectPacket {
		const reason = JSON.parse(reader.readString());
		return new ClientboundLoginDisconnectPacket(reason);
	}
}