// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import { Direction, State, type GameProfile } from '../../types';

export class ClientboundLoginFinishedPacket extends DripleafPacket {
	static readonly codec = packetCodec<ClientboundLoginFinishedPacket>({
		encode(writer: PacketWriter, value: ClientboundLoginFinishedPacket) {
		writer.writeUUID(value.profile.id);
		writer.writeString(value.profile.name);
		writer.writeVarInt(value.profile.properties.length);
		for (const property of value.profile.properties) {
			writer.writeString(property.name);
			writer.writeString(property.value);
			writer.writePrefixedOptional(property.signature, (signature) => writer.writeString(signature));
		}
		},
		decode(reader: PacketReader): ClientboundLoginFinishedPacket {
		const id = reader.readUUID();
		const name = reader.readString();
		const propertyCount = reader.readVarInt();
		const properties: { name: string; value: string; signature?: string | null }[] = [];
		for (let i = 0; i < propertyCount; i++) {
			const propertyName = reader.readString();
			const propertyValue = reader.readString();
			const signature = reader.readPrefixedOptional(() => reader.readString());
			properties.push({ name: propertyName, value: propertyValue, signature });
		}
		return new ClientboundLoginFinishedPacket({ id, name, properties });
		},
	});

	constructor(
		public profile: GameProfile
	) {
		super();
	}

}
