// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundLoginDisconnectPacket extends DripleafPacket {
	static readonly codec = packetCodec<ClientboundLoginDisconnectPacket>({
		encode(writer: PacketWriter, value: ClientboundLoginDisconnectPacket) {
		writer.writeString(JSON.stringify(value.reason));
		},
		decode(reader: PacketReader): ClientboundLoginDisconnectPacket {
		const reason = JSON.parse(reader.readString());
		return new ClientboundLoginDisconnectPacket(reason);
		},
	});

	constructor(
		public reason: Object,
	) {
		super();
	}

}
