// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { DripleafPacket, packetCodec } from '../DripleafPacket';
import { GameProfileCodec, type GameProfile } from '../../datatypes/GameProfile';

export class ClientboundLoginFinishedPacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundLoginFinishedPacket, {
		profile: GameProfileCodec,
	});

	constructor(
		public profile: GameProfile
	) {
		super();
	}
}