// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { type PacketReader, type PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ServerboundCustomQueryAnswerPacket extends DripleafPacket {
	static readonly codec = packetCodec({
		encode(writer: PacketWriter, value: ServerboundCustomQueryAnswerPacket) {
			writer.writeVarInt(value.messageId);
			writer.writePrefixedOptional(value.response, resp => writer.writeBytes(resp));
		},
		decode(reader: PacketReader): ServerboundCustomQueryAnswerPacket {
			return new ServerboundCustomQueryAnswerPacket(
				reader.readVarInt(),
				reader.readPrefixedOptional(() => reader.readRemaining()),
			);
		},
	});

	constructor(
		public messageId: number,
		public response: Uint8Array | null,
	) {
		super();
	}
}