// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ServerboundCustomQueryAnswerPacket extends DripleafPacket {
	static readonly codec = packetCodec<ServerboundCustomQueryAnswerPacket>({
		encode(writer: PacketWriter, value: ServerboundCustomQueryAnswerPacket) {
		writer.writeVarInt(value.messageId);
		writer.writeByteArray(value.response);
		},
		decode(reader: PacketReader): ServerboundCustomQueryAnswerPacket {
		const messageId = reader.readVarInt();
		const response = reader.readByteArray();
		return new ServerboundCustomQueryAnswerPacket(messageId, response);
		},
	});

	constructor(
		public messageId: number,
		public response: Uint8Array
	) {
		super();
	}

}
