// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ServerboundCustomQueryAnswerPacket extends DripleafPacket {
	static readonly codec = packetCodec(ServerboundCustomQueryAnswerPacket, {
		messageId: Codecs.varInt,
		response: Codecs.byteArray(),
	});

	constructor(
	public messageId: number,
			public response: Uint8Array
	) {
		super();
	}
}