// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ServerboundKeyPacket extends DripleafPacket {
	static readonly codec = packetCodec<ServerboundKeyPacket>({
		encode(writer: PacketWriter, value: ServerboundKeyPacket) {
		writer.writeByteArray(value.sharedSecret);
		writer.writeByteArray(value.verifyToken);
		},
		decode(reader: PacketReader): ServerboundKeyPacket {
		const sharedSecret = reader.readByteArray();
		const verifyToken = reader.readByteArray();
		return new ServerboundKeyPacket(sharedSecret, verifyToken);
		},
	});

	constructor(
		public sharedSecret: Uint8Array,
		public verifyToken: Uint8Array
	) {
		super();
	}

}
