// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ServerboundKeyPacket extends DripleafPacket {
	static readonly codec = packetCodec(ServerboundKeyPacket, {
		sharedSecret: Codecs.byteArray(),
		verifyToken: Codecs.byteArray(),
	});

	constructor(
		public sharedSecret: Uint8Array,
		public verifyToken: Uint8Array
	) {
		super();
	}
}