// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State } from '../../types';

export class ServerboundKeyPacket extends DripleafPacket {
	static readonly id = 0x01;
	static readonly state = State.Login;
	static readonly direction = Direction.Serverbound;

	override readonly id = ServerboundKeyPacket.id;
	override readonly state = ServerboundKeyPacket.state;
	override readonly direction = ServerboundKeyPacket.direction;

	constructor(
		public sharedSecret: Uint8Array,
		public verifyToken: Uint8Array
	) {
		super();
	}

	write(writer: PacketWriter) {
		writer.writeByteArray(this.sharedSecret);
		writer.writeByteArray(this.verifyToken);
	}

	static read(reader: PacketReader): ServerboundKeyPacket {
		const sharedSecret = reader.readByteArray();
		const verifyToken = reader.readByteArray();
		return new ServerboundKeyPacket(sharedSecret, verifyToken);
	}
}