// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State } from '../../types';

export class ServerboundLoginAcknowledgedPacket extends DripleafPacket {
	static readonly id = 0x03;
	static readonly state = State.Login;
	static readonly direction = Direction.Serverbound;

	override readonly id = ServerboundLoginAcknowledgedPacket.id;
	override readonly state = ServerboundLoginAcknowledgedPacket.state;
	override readonly direction = ServerboundLoginAcknowledgedPacket.direction;

	constructor() {
		super();
	}

	write(writer: PacketWriter) {
		return new Uint8Array();
	}

	static read(reader: PacketReader): ServerboundLoginAcknowledgedPacket {
		return new ServerboundLoginAcknowledgedPacket();
	}
}