name: test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: pnpm install

      - name: Verify generated data
        run: bun run codegen && git diff --exit-code

      - name: Run unit tests
        run: bun run test

      - name: Run typecheck
        run: bun run typecheck
