name: test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: pnpm install

      - name: Run unit tests
        run: bun test packages/nbt/tests packages/registry/tests packages/world/tests packages/pathfinder/tests packages/inventory/tests
