// This file is generated by codegen/util/tags.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Fluid } from "../builtin";

const BubbleColumnCanOccupy = [
	Fluid.Water,
] as const;

const Lava = [
	Fluid.Lava,
	Fluid.FlowingLava,
] as const;

const SupportsFrogspawn = [
	Fluid.Water,
] as const;

const SupportsLilyPad = [
	Fluid.Water,
] as const;

const SupportsSugarCaneAdjacently = [
	Fluid.Water,
	Fluid.FlowingWater,
] as const;

const Water = [
	Fluid.Water,
	Fluid.FlowingWater,
] as const;

export { BubbleColumnCanOccupy, Lava, SupportsFrogspawn, SupportsLilyPad, SupportsSugarCaneAdjacently, Water };